workarea-commerce/workarea

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-15.html.md

v3.4.15 Patch Release Notes

---

core/lib/workarea/configuration/mongoid.rb
core/lib/workarea/warnings.rb

Only check notablescan in development

---

core/app/queries/workarea/product_releases.rb
core/test/queries/workarea/product_releases_test.rb

Fix product search indexing when changesets are missing a release

---

core/app/queries/workarea/reports/customers.rb
core/test/queries/workarea/reports/customers_test.rb

Bugfix 41 reports divide by zero

---

core/app/middleware/workarea/query_cache_middleware.rb
core/app/queries/workarea/featured_categorization.rb
core/app/queries/workarea/product_primary_navigation.rb
core/app/workers/workarea/index_admin_search.rb
core/app/workers/workarea/index_categorization.rb
core/app/workers/workarea/index_category.rb
core/app/workers/workarea/index_category_changes.rb
core/app/workers/workarea/index_fulfillment_changes.rb
core/app/workers/workarea/index_help.rb
core/app/workers/workarea/index_page.rb
core/app/workers/workarea/index_payment_transactions.rb
core/app/workers/workarea/index_product.rb
core/app/workers/workarea/index_product_children.rb
core/app/workers/workarea/index_product_rule.rb
core/app/workers/workarea/index_search_customizations.rb
core/app/workers/workarea/index_skus.rb
core/app/workers/workarea/keep_product_index_fresh.rb
core/lib/workarea/configuration/sidekiq.rb
core/test/middleware/workarea/query_cache_middleware_test.rb

Indexing performance

---

admin/config/locales/en.yml

Fix "Back To" links in Releases flow

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-3-34.html.md
docs/source/release-notes/workarea-3-4-16.html.md

Patch Release Notes for v3.4.16 and v3.3.34

---

core/app/models/workarea/pricing/discount/application_group.rb
core/app/models/workarea/pricing/discount/free_gift.rb
core/lib/workarea/ext/freedom_patches/action_view_cache_helper.rb
storefront/app/helpers/workarea/storefront/content_helper.rb
storefront/test/helpers/workarea/storefront/content_helper_test.rb

Improvement 43 release cache keys

---

docs/source/release-notes.html.md

Fixes a small typo in the release notes index

Fix Typo in Release Notes Index

---

docs/source/articles/add-a-fraud-analyzer.html.md
docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-5-0.html.md
docs/source/upgrade-guides.html.md
docs/source/upgrade-guides/workarea-3-5-0.html.md

(This is an initial commit to provide a starting point for the release
notes and will be edited and expanded in future commits)
* Add 3.5 release notes doc
* Link to 3.5 release notes doc from release notes index
* Rename and modify 3.5 upgrade guide for consistency with 3.4 upgrade guide
* Cross-reference 3.5 release notes and upgrade guide

Add Workarea 3.5 release notes

---

docs/source/index.html.erb
docs/source/layouts/article.erb
docs/source/layouts/bare.erb
docs/source/layouts/layout.erb
docs/source/stylesheets/_components.scss

Add GitHub ribbon to developer docs

---

.github/actions/build_documentation/Dockerfile
.github/actions/build_documentation/action.yml
.github/actions/build_documentation/documentation/Gemfile
.github/actions/build_documentation/documentation/build.rb
.github/actions/build_documentation/documentation/s3.rb
.github/actions/build_documentation/entrypoint.sh
.github/workflows/documentation.yml
docs/source/images/styles.css

This is functional, but the issues with middleman and therubyracer need to be resolved before this gets merged otherwise it will break the doc site. Figured I'd open this for comment in the meantime

Add documentation build action and workflow

---

docs/source/cli.html.md

Fix typos in CLI documentation

---

core/app/models/workarea/order.rb
core/config/initializers/00_configuration.rb
core/config/locales/en.yml
core/test/models/workarea/order_test.rb

Add config field to limit total item count for a single cart

---

admin/app/controllers/workarea/admin/fulfillment_tokens_controller.rb
admin/app/view_models/workarea/admin/fulfillment_token_view_model.rb
admin/app/view_models/workarea/admin/fulfillment_view_model.rb
admin/app/views/workarea/admin/fulfillment_tokens/index.html.haml
admin/app/views/workarea/admin/fulfillments/show.html.haml
admin/app/views/workarea/admin/orders/_cards.html.haml
admin/config/locales/en.yml
core/app/models/workarea/fulfillment/token.rb

* Change package messaging for items with no carrier and tracking number
* Add table of fulfillment tokens associated to an order
* Fix paginating fulfillment tokens
Closes #93

Refine fullfillment UI around skus and tokens

---

README.md

Fix duplication in README

---

docs/source/articles/seeds.html.md

Replace incorrect admin email/password with instructions to find this
information, since it tends to change over time, and apps and plugins
can also change the default users and add additional users.
No changelog

Fix information about seeded emails/passwords

---

docs/source/articles/inventory.html.md

Add coverage of inventory collection status, a new concept
in Workarea 3.5

Update inventory docs for Workarea 3.5 (#98)

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-17.html.md

v3.4.17 Patch Release Notes

---

admin/app/views/workarea/admin/tax_rates/index.html.haml
admin/test/system/workarea/admin/tax_categories_system_test.rb

Remove Combined Tax column from Tax Rates index table (#96)

---

admin/app/assets/stylesheets/workarea/admin/components/_activity.scss
admin/app/assets/stylesheets/workarea/admin/components/_activity_group.scss
admin/app/assets/stylesheets/workarea/admin/components/_date_marker.scss
admin/app/views/workarea/admin/activities/show.html.haml
admin/app/views/workarea/admin/orders/timeline.html.haml
admin/app/views/workarea/admin/style_guides/components/_activity.html.haml
admin/app/views/workarea/admin/style_guides/components/_activity_group.html.haml
admin/app/views/workarea/admin/style_guides/components/_release_changeset.html.haml
admin/app/views/workarea/admin/timeline/show.html.haml
admin/app/views/workarea/admin/trash/index.html.haml
admin/config/locales/en.yml
admin/test/system/workarea/admin/orders_system_test.rb

The `activity`, `activity-group`, and `date-marker` UIs couple together
to create, what's unofficially referred to as, The Timeline UI. These
components have been neglected for a long time... until now!
Closes #58

Spruce up Timeline UI

---

admin/app/views/workarea/admin/segment_rules/fields/_logged_in.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_tags.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_logged_in.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_tags.html.haml
admin/config/locales/en.yml
core/app/models/workarea/metrics/user.rb
core/app/models/workarea/segment/rules/logged_in.rb
core/app/models/workarea/segment/rules/tags.rb
core/app/workers/workarea/synchronize_user_metrics.rb
core/lib/workarea/configuration.rb
core/lib/workarea/visit.rb
core/test/models/workarea/segment/rules/logged_in_test.rb
core/test/models/workarea/segment/rules/tags_test.rb
core/test/queries/workarea/search/admin_users_test.rb
core/test/workers/workarea/synchronize_user_metrics_test.rb
storefront/test/integration/workarea/storefront/analytics_integration_test.rb
storefront/test/integration/workarea/storefront/segments_integration_test.rb
testing/lib/workarea/testing/factories/segment.rb

For whether the visitor is logged in and whether they're tagged.
No changelog
This is pointing at my branch for activeness for now.

Add additional segment rules

---

core/app/controllers/workarea/authentication.rb
core/app/models/workarea/content/asset.rb
core/app/models/workarea/content/block_type_definition.rb
core/app/models/workarea/order/item.rb
core/app/models/workarea/search/storefront/product/categories.rb
storefront/app/helpers/workarea/storefront/favicons_helper.rb
testing/lib/workarea/test_case.rb

This'll be easier to digest after #135 merges, might want to wait until then to peep.

Use deprecator

---

admin/app/views/workarea/admin/users/insights.html.haml
core/app/models/workarea/metrics/update_user_aggregations.rb
core/app/models/workarea/metrics/user.rb
core/test/models/workarea/metrics/update_user_aggregations_test.rb

Now that metrics can be created upfront, we'll need to handle this.
No changelog

Fix zero-order user aggregations

---

core/app/models/workarea/pricing/cache_key.rb
core/app/models/workarea/pricing/calculator.rb
core/app/models/workarea/pricing/calculators/tax_calculator.rb
core/app/models/workarea/pricing/item_tax_applier.rb
core/app/models/workarea/pricing/request.rb
core/app/models/workarea/pricing/tax_application.rb
core/app/models/workarea/pricing/tax_applier.rb
core/test/models/workarea/pricing/cache_key_test.rb
core/test/models/workarea/pricing/calculators/tax_calculator_test.rb
core/test/models/workarea/pricing/item_tax_applier_test.rb
core/test/models/workarea/pricing/request_test.rb
storefront/test/system/workarea/storefront/download_system_test.rb

* Adds Payment lookup to pricing request
* Modifies TaxCalculator to check shipped and not shipped items
* Renames TaxApplier to ShippedTaxApplier, Uses TaxApplier for not shipped items
Work for #91

Apply tax to items that do not require shipping

---

README.md

Update "Getting Started" in README

---

core/app/models/workarea/featured_products.rb
core/app/queries/workarea/categorization.rb
core/app/queries/workarea/featured_categorization.rb
core/test/queries/workarea/featured_categorization_test.rb

Rework FeaturedCategorizations to allow easier decoration

---

core/lib/tasks/migrate.rake
docs/source/upgrade-guides/workarea-3-5-0.html.md

Add segment migration to upgrade guide and migration task

---

core/app/models/workarea/pricing/request.rb

Fix Payment cloning in Pricing::Request

---

admin/test/system/workarea/admin/impersonation_system_test.rb
storefront/test/system/workarea/storefront/release_browsing_system_test.rb
testing/lib/workarea/system_test.rb

* Move #wait_for_iframe to SystemTest class
* Add #within_frame to methods that wait for xhr requests
* Use #wait_for_iframe on spotty ImpersonationSystem Test

Modify SystemTest to help increase reliability of #within_frame

---

admin/app/assets/stylesheets/workarea/admin/components/_box.scss
admin/app/views/workarea/admin/create_segments/rules.html.haml
admin/app/views/workarea/admin/segment_rules/_form.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_last_order.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_orders.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_revenue.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_sessions.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_tags.html.haml
admin/app/views/workarea/admin/segment_rules/fields/_traffic_referrer.html.haml
admin/app/views/workarea/admin/segment_rules/index.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_geolocation.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_last_order.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_logged_in.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_orders.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_revenue.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_sessions.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_tags.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_traffic_referrer.html.haml
admin/app/views/workarea/admin/segments/_cards.html.haml
admin/app/views/workarea/admin/style_guides/components/_box.html.haml
admin/config/locales/en.yml
core/lib/workarea/visit.rb

Clean up Segement Rules UI

---

admin/app/views/workarea/admin/configurations/show.html.haml
admin/app/views/workarea/admin/dashboards/settings.html.haml
admin/config/locales/en.yml

Remove repetitive 'configuration' prefix from config section titles

---

admin/app/views/workarea/admin/catalog_categories/_cards.html.haml
admin/app/views/workarea/admin/dashboards/reports.html.haml
admin/app/views/workarea/admin/shared/_primary_nav.html.haml
admin/config/locales/en.yml

These are from demoing in Toronto.

Small admin ui tweaks

---

admin/app/views/workarea/admin/content/advanced.html.haml
admin/config/locales/en.yml
core/app/models/workarea/content.rb
docs/source/articles/add-javascript-through-the-admin-ui.html.md
storefront/app/helpers/workarea/storefront/application_helper.rb
storefront/app/view_models/workarea/storefront/display_content.rb
storefront/app/views/layouts/workarea/storefront/application.html.haml
storefront/app/views/layouts/workarea/storefront/content_preview.html.haml
storefront/app/views/layouts/workarea/storefront/empty.html.haml
storefront/app/views/workarea/storefront/categories/show.html.haml
storefront/app/views/workarea/storefront/content_areas/show.html.haml
storefront/app/views/workarea/storefront/errors/show.html.haml
storefront/app/views/workarea/storefront/pages/home_page.html.haml
storefront/app/views/workarea/storefront/pages/show.html.haml

Add JavaScript field for output in head to Content

---

storefront/test/system/workarea/storefront/segment_overrides_system_test.rb

Add #wait_for_iframe to segment override test for more consistent result

---

admin/app/assets/javascripts/workarea/admin/modules/active_by_segment_tooltips.js

Improve UX around Active By Segment tooltips

---

.rubocop.yml

Fix for newest rubocop

---

core/app/models/workarea/data_file/csv_fields.rb
core/test/models/workarea/data_file/csv_fields_test.rb

Adds graceful handling of timestamps from CSV imports

---

admin/app/view_models/workarea/admin/discounts/buy_some_get_some_view_model.rb
admin/app/view_models/workarea/admin/discounts/category_view_model.rb
admin/app/view_models/workarea/admin/discounts/free_gift_view_model.rb
admin/app/view_models/workarea/admin/discounts/order_total_view_model.rb
admin/app/view_models/workarea/admin/discounts/product_attribute_view_model.rb
admin/app/view_models/workarea/admin/discounts/product_view_model.rb
admin/app/view_models/workarea/admin/discounts/quantity_fixed_price_view_model.rb
admin/app/view_models/workarea/admin/discounts/shipping_view_model.rb

Fix selected discount conditions when editing

---

admin/app/controllers/workarea/admin/comments_controller.rb
admin/app/views/workarea/admin/comments/index.html.haml
admin/config/locales/en.yml
admin/config/routes.rb
admin/test/integration/workarea/admin/comments_integration_test.rb
admin/test/system/workarea/admin/comments_system_test.rb

Add buttons to allow admin users to subscribe/unsubscribe from comments

---

admin/app/assets/javascripts/workarea/admin/config.js.erb
admin/app/assets/stylesheets/workarea/admin/components/_content_block.scss
admin/app/controllers/workarea/admin/users_controller.rb
admin/app/views/workarea/admin/content/_edit.html.haml
admin/test/integration/workarea/admin/pricing_overrides_integration_test.rb
core/app/controllers/workarea/authentication.rb
core/app/controllers/workarea/current_segments.rb
core/app/middleware/workarea/application_middleware.rb
core/app/models/workarea/metrics/user.rb
core/app/models/workarea/segment/first_time_visitor.rb
core/app/models/workarea/segment/returning_customer.rb
core/app/models/workarea/segment/returning_visitor.rb
core/app/models/workarea/user/authorization.rb
core/app/workers/workarea/synchronize_user_metrics.rb
core/config/initializers/13_rack_attack.rb
core/lib/workarea/visit.rb
core/test/integration/workarea/authentication_test.rb
core/test/models/workarea/user_test.rb
core/test/workers/workarea/synchronize_user_metrics_test.rb
storefront/test/integration/workarea/storefront/segment_overrides_integration_test.rb
storefront/test/integration/workarea/storefront/segments_integration_test.rb
storefront/test/system/workarea/storefront/analytics_system_test.rb
storefront/test/system/workarea/storefront/pricing_overrides_system_test.rb
storefront/test/system/workarea/storefront/segment_overrides_system_test.rb

Probably easiest to review by the individual commits.

Segments qa stuff

---

admin/app/view_models/workarea/admin/order_view_model.rb
admin/app/views/workarea/admin/catalog_categories/_cards.html.haml
admin/app/views/workarea/admin/catalog_products/_cards.html.haml
admin/app/views/workarea/admin/content_pages/_cards.html.haml
admin/app/views/workarea/admin/orders/_cards.html.haml
admin/app/views/workarea/admin/orders/attributes.html.haml
admin/app/views/workarea/admin/orders/fraud.html.haml
admin/app/views/workarea/admin/pricing_discounts/_cards.html.haml
admin/app/views/workarea/admin/search_customizations/_cards.html.haml
admin/config/locales/en.yml

Show segments throughout the admin

Improve segments admin visibility

---

core/app/queries/workarea/search/storefront_search.rb
core/test/queries/workarea/search/storefront_search_test.rb

Fix search customizations to be null object instead of nil when inactive

---

admin/app/views/workarea/admin/releases/index.html.haml

Add "Add to Calendar" UI to Release Calendar

---

admin/app/controllers/workarea/admin/segmentables_controller.rb
admin/app/helpers/workarea/admin/facets_helper.rb
admin/app/view_models/workarea/admin/segment_view_model.rb
admin/app/views/workarea/admin/content/_card.html.haml
admin/app/views/workarea/admin/segmentables/index.html.haml
admin/app/views/workarea/admin/segments/_cards.html.haml
admin/config/locales/en.yml
admin/config/routes.rb
admin/test/system/workarea/admin/segments_system_test.rb
core/app/models/workarea/releasable.rb
core/app/models/workarea/search/admin/releasable.rb
core/app/models/workarea/segment/life_cycle.rb
core/app/models/workarea/segmentable.rb
core/app/queries/workarea/search/admin_index_search.rb
core/lib/workarea/core.rb
core/lib/workarea/ext/mongoid/embedded_children.rb
core/test/lib/workarea/ext/mongoid/embedded_children_test.rb
core/test/models/workarea/search/admin/releasable_test.rb
core/test/models/workarea/segment/life_cycle_test.rb
core/test/models/workarea/segmentable_test.rb

This adds "Active by Segment" as a filter, and adds a "Content" card to
segments to surface what stuff has been setup specifically for a
segment.
WORKAREA-89

Add admin browsing by segmentable content

---

testing/lib/workarea/generator_test.rb
testing/lib/workarea/integration_test.rb
testing/lib/workarea/mailer_test.rb
testing/lib/workarea/test_case.rb
testing/lib/workarea/view_test.rb

Also refactor setup/teardown so we can share that in one spot.
No changelog

Fix segment content resetting in tests

---

admin/app/helpers/workarea/admin/segments_helper.rb
admin/app/views/workarea/admin/segment_rules/fields/_last_order.html.haml
admin/app/views/workarea/admin/segment_rules/summaries/_last_order.html.haml
admin/config/locales/en.yml
core/app/models/workarea/segment/rules/last_order.rb
core/test/models/workarea/segment/rules/last_order_test.rb

Expand last order segment rule to allow not ordered within

---

docs/source/release-notes/workarea-3-5-0.html.md
docs/source/upgrade-guides/workarea-3-5-0.html.md

* Add link to community preview video
* Add changes since last update
* Improve "callouts" at top of each doc
* Use consistent style
WORKAREA-16
No changelog

Update v3.5 release notes and upgrade guide

---

admin/app/assets/javascripts/workarea/admin/modules/toggle_elements.js
admin/app/views/workarea/admin/segments/_publish.html.haml
admin/test/system/workarea/admin/segments_system_test.rb

Fix segement selection on publish step of workflows

---

admin/app/assets/javascripts/workarea/admin/config.js.erb
admin/app/assets/javascripts/workarea/admin/modules/timeline_report_chart.js
admin/app/assets/javascripts/workarea/admin/templates/chart_legend.jst.ejs
admin/app/assets/stylesheets/workarea/admin/application.scss.erb
admin/app/assets/stylesheets/workarea/admin/components/_button.scss
admin/app/assets/stylesheets/workarea/admin/components/_chart_legend.scss
admin/app/assets/stylesheets/workarea/admin/components/_timeline_report.scss
admin/app/assets/stylesheets/workarea/admin/settings/_grid.scss
admin/app/controllers/workarea/admin/custom_events_controller.rb
admin/app/view_models/workarea/admin/reports/timeline_view_model.rb
admin/app/views/workarea/admin/releases/edit.html.haml
admin/app/views/workarea/admin/releases/list.html.haml
admin/app/views/workarea/admin/reports/timeline.html.haml
admin/config/locales/en.yml
admin/config/routes.rb
admin/test/integration/workarea/admin/custom_events_integration_test.rb
admin/test/system/workarea/admin/reports_system_test.rb
core/app/models/workarea/reports/custom_event.rb
core/workarea-core.gemspec

Add Custom Events to Timeline Report

---

admin/app/assets/javascripts/workarea/admin/modules/impersonation_notification.js
admin/app/views/layouts/workarea/admin/application.html.haml
admin/config/locales/en.yml

Extend impersonation notification to guest browsing

---

admin/app/helpers/workarea/admin/icons_helper.rb
admin/app/views/workarea/admin/catalog_categories/_cards.html.haml
admin/app/views/workarea/admin/catalog_categories/index.html.haml
admin/app/views/workarea/admin/catalog_products/_cards.html.haml
admin/app/views/workarea/admin/catalog_products/index.html.haml
admin/app/views/workarea/admin/content/_edit.html.haml
admin/app/views/workarea/admin/content/_form.html.haml
admin/app/views/workarea/admin/content_pages/_cards.html.haml
admin/app/views/workarea/admin/content_pages/index.html.haml
admin/app/views/workarea/admin/navigation_menus/index.html.haml
admin/app/views/workarea/admin/pricing_discounts/_cards.html.haml
admin/app/views/workarea/admin/pricing_discounts/index.html.haml
admin/app/views/workarea/admin/search_customizations/_cards.html.haml
admin/app/views/workarea/admin/search_customizations/index.html.haml
admin/app/views/workarea/admin/shared/_active_field.html.haml
admin/config/locales/en.yml
core/app/models/workarea/segmentable.rb

Add warnings for content orphaned by segment deletion

---

admin/app/views/workarea/admin/content_assets/edit.html.haml
admin/app/views/workarea/admin/content_assets/new.html.haml
admin/config/locales/en.yml

Add special tags information tooltip to content asset tags field

---

README.md
docs/source/articles/create-a-new-app.html.md

Add Quick Start video to README and docs

---

admin/app/helpers/workarea/admin/activities_helper.rb
admin/app/views/workarea/admin/activities/_create.html.haml
admin/app/views/workarea/admin/activities/_destroy.html.haml
admin/app/views/workarea/admin/activities/_update.html.haml
admin/config/locales/en.yml

Clean up generic admin activity view partials

---

admin/app/controllers/workarea/admin/content_assets_controller.rb
admin/test/integration/workarea/admin/assets_integration_test.rb
core/app/services/workarea/direct_upload.rb
core/test/services/workarea/direct_upload_test.rb

Fix content block asset uploads, set redis key to reduce S3 CORS config requests

---

admin/app/helpers/workarea/admin/application_helper.rb
admin/app/view_models/workarea/admin/alerts_view_model.rb
admin/app/views/layouts/workarea/admin/application.html.haml
admin/config/locales/en.yml
admin/test/helpers/workarea/admin/application_helper_test.rb
core/app/queries/workarea/alerts.rb
core/lib/workarea/core.rb
core/lib/workarea/latest_version.rb
core/lib/workarea/ping_home_base.rb
core/test/lib/workarea/latest_version_test.rb
core/test/vcr_cassettes/get_latest_version.yml

Add admin alert when a newer workarea version is available

---

admin/app/helpers/workarea/admin/application_helper.rb
admin/app/views/workarea/admin/pricing_discounts/edit.html.haml
admin/config/locales/en.yml
admin/test/helpers/workarea/admin/application_helper_test.rb
core/app/models/workarea/pricing/discount.rb
core/app/workers/workarea/deactivate_stale_discounts.rb
core/config/locales/en.yml
core/test/workers/workarea/deactivate_stale_discounts_test.rb

Base discount auto-deactivation on updated_at, expose auto_deactivate field

---

admin/app/views/layouts/workarea/admin/application.html.haml
admin/config/locales/en.yml

Fix broken translation and update language to sound less technical

---

.github/workflows/documentation.yml
docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-22.html.md

Also updated the docs workflow so it will build from master.

Patch Release Notes for v3.4.22

---

core/app/models/workarea/content/block_draft.rb

Remove Releasable module from Content::BlockDraft

---

admin/test/system/workarea/admin/content_system_test.rb

Fix segment-based content system test

---

admin/test/system/workarea/admin/content_system_test.rb

Yank Content system test around segments

---

core/app/queries/workarea/search/product_search.rb
core/test/queries/workarea/search/product_search_test.rb

Fix nil search customizations when inactive in ProductSearch

---

core/app/models/workarea/data_file/csv.rb
core/test/models/workarea/data_file/csv_test.rb

Fix polymorphic embedded relations in CSV importing/exporting

---

.github/workflows/ci.yml

Update github workflow to ignore paths that do not require CI runs

---

admin/app/view_models/workarea/admin/content_view_model.rb
admin/app/views/workarea/admin/content/_edit.html.haml
admin/test/view_models/workarea/admin/content_view_model_test.rb

This can happen in certain release conditions
WORKAREA-111

Fix adding a new first content block hidden

---

admin/app/views/workarea/admin/create_releases/setup.html.haml
admin/app/views/workarea/admin/releases/_publish.html.haml
admin/app/views/workarea/admin/releases/edit.html.haml

Restrict release datetimepicker to dates in the future

---

.rubocop.yml

Update cops names for newest version of rubocop

---

core/app/models/workarea/pricing/discount/redemption.rb

As suggested by the hosting team.

Add index for better redemption querying

---

.github/workflows/documentation.yml

Build docs from branch v3.5-stable

---

core/lib/workarea/core.rb

The `workarea:install` generator failed with an error finding the
`Storefront::Engine` constant when it was run against a freshly
generated Rails 5.2.3 application. To resolve this, require the
necessary engines in **lib/workarea/core.rb** so the application loads
properly the first time, and can run the generator.
Test Results
------------
The first was an "attempt" to run `rails g workarea:install` in a fresh
app created from the latest 3.4 patch on RubyGems. The failure is to
show what happens in the real world. The next attempt succeeds by
installing this branch of Workarea and re-running the generator.
```
$ mkdir testapp && cd testapp && bundle init && bundle add workarea -v '~> 3.4' && bundle exec rails new . --no-rc --skip-spring --skip-active-record --skip-action-cable …
```

Fix Install Generator On Freshly Created App

---

.github/workflows/ci.yml

Add screenshots for system test failures

---

docs/source/cli.html.md

Update CLI Cheat Sheet

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-23.html.md
docs/source/release-notes/workarea-3-5-1.html.md

Patch Release Notes for v3.4.23 and v3.5.1

---

admin/app/views/layouts/workarea/admin/application.html.haml
admin/config/locales/en.yml

Add a Shortcut for editing the Footer to Admin

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-0-68.html.md
docs/source/release-notes/workarea-3-1-55.html.md
docs/source/release-notes/workarea-3-2-44.html.md
docs/source/release-notes/workarea-3-3-36.html.md
docs/source/release-notes/workarea-3-4-24.html.md
docs/source/release-notes/workarea-3-5-2.html.md

Add release notes for v3.5.2

---

admin/app/views/workarea/admin/dashboards/index.html.haml

Reuse new Activity UI for main dashboard in Admin

---

storefront/test/integration/workarea/storefront/checkouts_integration_test.rb
testing/lib/workarea/storefront/integration_test.rb

These were causing build failures. Assuming these fixes got lost in a
merge.

Fix some references to 2020

---

testing/lib/workarea/storefront/integration_test.rb

We've all learned our lesson, right?

Another hardcoded 2020 fix

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-25.html.md
docs/source/release-notes/workarea-3-5-3.html.md

Patch Release Notes for v3.4.25 and v3.5.3

---

core/app/models/workarea/release.rb
core/app/models/workarea/release/changeset.rb
core/lib/workarea/configuration.rb
core/test/models/workarea/release_test.rb

Order release changesets during publishing, touch releasables after publish

---

docs/data/articles.yml
docs/source/articles/add-a-test-factory.html.md
docs/source/articles/add-or-change-test-factories-and-support.html.md
docs/source/articles/configure-test-factories.html.md
docs/source/articles/decorate-and-write-tests.html.md
docs/source/articles/run-tests.html.md
docs/source/articles/testing-overview.html.md

Update/complete "Testing" docs outline

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-26.html.md
docs/source/release-notes/workarea-3-5-4.html.md

Patch Release Notes for v3.4.26 and v3.5.4

---

.github/actions/build_documentation/documentation/build.rb

Add logging when an exception is swallowed when building docs

---

admin/app/views/workarea/admin/shipping_services/edit.html.haml
admin/app/views/workarea/admin/shipping_services/new.html.haml
admin/config/locales/en.yml
admin/test/integration/workarea/admin/shipping_service_integration_test.rb

Expose shipping service code in admin create and edit screens

---

core/app/workers/sidekiq/callbacks.rb
core/test/workers/sidekiq/callbacks_test.rb

And that's why you always write a test.
No changelog

Fix bug in previous Sidekiq callbacks patch

---

.github/ISSUE_TEMPLATE/documentation-request.md
docs/source/layouts/article.erb

Remove GitHub assignee for docs issues

---

.github/workflows/ci.yml
admin/app/assets/javascripts/workarea/admin/modules/release_reminder.js
core/test/javascripts/form_submitting_controls_spec.js
storefront/test/javascripts/traffic_referrer_spec.js

Enable Teaspoon in CI

---

admin/app/views/workarea/admin/content_assets/_summary.html.haml
admin/app/views/workarea/admin/content_assets/insert.html.haml

Add image dimensions to Asset summaries

---

.eslintrc.json
.github/workflows/ci.yml
Gemfile
admin/app/assets/javascripts/workarea/admin/modules/release_reminder.js
admin/test/javascripts/release_reminder_spec.js
core/test/javascripts/form_submitting_controls_spec.js
core/workarea-core.gemspec
storefront/test/javascripts/forms_spec.js
storefront/test/javascripts/traffic_referrer_spec.js

This was no longer running properly due to a strange `coffee_rails`
dependency. More information here:
https://github.com/jejacks0n/teaspoon/issues/405
WORKAREA-185

Fix Teaspoon in CI

---

CONTRIBUTING.md

Noticed this while learning how to contribute.

update contribute links

---

storefront/app/views/workarea/storefront/shared/_address_fields.html.haml

Repeated code in update_address_fields.html.haml

Fix code repetition

---

admin/app/assets/javascripts/workarea/admin/modules/content_editor_forms.js
admin/app/assets/javascripts/workarea/admin/modules/toggle_elements.js
admin/app/views/workarea/admin/content/_form.html.haml
admin/config/locales/en.yml
admin/test/system/workarea/admin/content_system_test.rb
core/app/models/workarea/content/block.rb

Allow custom naming of Content Blocks

---

core/app/assets/javascripts/workarea/core/modules/image.js
storefront/app/assets/javascripts/workarea/storefront/application.js.erb
storefront/app/assets/javascripts/workarea/storefront/modules/lazy_images.js
storefront/app/assets/stylesheets/workarea/storefront/base/_images.scss
storefront/app/helpers/workarea/storefront/application_helper.rb
storefront/app/views/workarea/storefront/cart_items/create.html.haml
storefront/app/views/workarea/storefront/carts/show.html.haml
storefront/app/views/workarea/storefront/checkouts/payment.html.haml
storefront/app/views/workarea/storefront/orders/_summary.html.haml
storefront/app/views/workarea/storefront/products/_summary.html.haml
storefront/app/views/workarea/storefront/products/templates/_generic.html.haml
storefront/app/views/workarea/storefront/products/templates/_option_selects.html.haml
storefront/app/views/workarea/storefront/products/templates/_option_thumbnails.html.haml
storefront/test/javascripts/lazy_images_spec.js

Allow images to be lazy loaded

---

docs/source/upgrade-guides/workarea-3-5-0.html.md

Several builds have hit this in their upgrade.
No changelog
WORKAREA-170

Add Redis cache store change to v3.5 upgrade guide

---

docs/source/articles/run-tests.html.md

Fix typo in docs example command

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-27.html.md
docs/source/release-notes/workarea-3-5-5.html.md

Patch Release Notes for v3.4.27 and v3.5.5

---

docs/source/release-notes/workarea-3-4-27.html.md
docs/source/release-notes/workarea-3-5-5.html.md

These changes didn't actually go out this time, will be on the next
release. Sorry for the confusion.

Fix Patch Release Notes

---

docs/source/javascripts/site.js
docs/source/search.html.erb
docs/source/stylesheets/_components.scss

Return a link to a github page when plugin match is found in docs search

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-28.html.md
docs/source/release-notes/workarea-3-5-6.html.md

Patch Release Notes for v3.4.28 and v3.5.6

---

admin/app/views/workarea/admin/pricing_skus/_cards.html.haml
admin/app/views/workarea/admin/pricing_skus/edit.html.haml
admin/app/views/workarea/admin/pricing_skus/index.html.haml
admin/app/views/workarea/admin/pricing_skus/new.html.haml

New PR to correct branch
- Add append points to `index` view
- Align `new`, `edit`, and `cards` views

Add append points and align views

---

admin/app/view_models/workarea/admin/pricing_sku_view_model.rb
admin/test/view_models/workarea/admin/pricing_sku_view_model_test.rb

Ensure that price ranges in the pricing SKUs admin index can handle when
there are no prices for the SKU.

Handle Missing Price in Pricing SKUs Admin Index

---

core/app/models/workarea/search/storefront.rb
core/app/models/workarea/search/storefront/product.rb
core/lib/workarea/core/engine.rb
core/test/models/workarea/search/storefront_test.rb
core/test/queries/workarea/search/product_search_test.rb

Also includes... 
BONUS fix: no more uninitialized constant BulkIndexProducts in development env.

Fix missing relation changesets in storefront indexing

---

admin/app/view_models/workarea/admin/pricing_sku_view_model.rb
admin/app/views/workarea/admin/pricing_skus/index.html.haml

Handle missing price in sell_price method itself

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-29.html.md
docs/source/release-notes/workarea-3-5-7.html.md

Patch Release Notes for v3.5.7 and v3.4.29

---

docs/source/release-notes.html.md
docs/source/release-notes/workarea-3-4-30.html.md
docs/source/release-notes/workarea-3-5-8.html.md

Add release notes for today's release

---

admin/app/assets/javascripts/workarea/admin/templates/content_block_iframe.jst.ejs
admin/test/system/workarea/admin/publish_authorization_system_test.rb

Fix reliability of system test

---

core/test/queries/workarea/search/product_search_test.rb

Skip localized activeness test when localized active fields are off

---

core/app/models/workarea/order.rb
core/app/models/workarea/pricing/order_totals.rb
core/test/models/workarea/pricing_test.rb
storefront/app/helpers/workarea/storefront/analytics_helper.rb
storefront/test/system/workarea/storefront/analytics_system_test.rb

This is a bunch of stuff that's been added in some builds and/or would be useful for plugins.

Add some analytics data

---

admin/app/views/workarea/admin/comments/index.html.haml
admin/config/locales/en.yml
admin/test/system/workarea/admin/comments_system_test.rb

Also improves UI to move the secondary action of
subscribing/unsubscribing out of the main area.

Fix comment subscription messaging

---

core/app/services/workarea/direct_upload.rb
core/test/services/workarea/direct_upload_test.rb

Handle error from attempting to fetch missing S3 CORS configuration

---

core/app/models/workarea/order.rb
core/app/models/workarea/release/changeset.rb

Add index for releasable fields on changets, correct order fraud index

---

core/lib/tasks/search.rake
core/lib/workarea/core.rb
core/lib/workarea/queues_pauser.rb

Add QueuePauser to pause sidekiq queues, pause for search reindexing

---

admin/app/views/workarea/admin/catalog_products/content.html.haml
admin/app/views/workarea/admin/catalog_products/edit.html.haml
admin/app/views/workarea/admin/catalog_variants/edit.html.haml
admin/app/views/workarea/admin/inventory_skus/edit.html.haml

Adds additional append points to product content, product details and filters, and inventory skus.

Add additional append points to admin system.

---

core/workarea-core.gemspec

Bump rack version

---

admin/app/controllers/workarea/admin/users_controller.rb
admin/app/view_models/workarea/admin/user_view_model.rb
admin/app/views/workarea/admin/users/_cards.html.haml
admin/app/views/workarea/admin/users/cart.html.haml
admin/config/locales/en.yml
admin/config/routes.rb
admin/test/system/workarea/admin/users_system_test.rb

Add admin cart for user cart, add detail page for latest cart

---

core/config/initializers/00_configuration.rb
core/config/initializers/13_rack_attack.rb
core/test/integration/workarea/rack_attack_integration_test.rb

Add admin configuration fields for safe/block listing IP addresses

---

docs/source/articles/add-catalog-customizations.html.md

Add a "how-to" guide that explains the setup of catalog customizations,
as well as the additional pricing charge, since there's nothing that
currently documents this out-of-box solution for customized products.

Add Catalog Customizations Guide

---

core/app/models/workarea/inquiry.rb
core/config/locales/en.yml
storefront/app/view_models/workarea/storefront/inquiry_view_model.rb

Allow inquiry subjects to be localized

---

core/app/controllers/workarea/impersonation.rb

This surfaced as a random failing test, this should make the feature more robust.

Handle missing or invalid current impersonation

---

admin/app/view_models/workarea/admin/user_view_model.rb
admin/app/views/workarea/admin/users/_cards.html.haml
admin/app/views/workarea/admin/users/edit.html.haml
admin/config/locales/en.yml

Display the `last_login_at` and `last_login_attempted_at` properties of a User on the attributes card in admin.

Show User Login Tracking Info in Admin

---

admin/app/view_models/workarea/admin/product_view_model.rb
admin/app/view_models/workarea/admin/variant_view_model.rb
admin/app/views/workarea/admin/bulk_action_sequential_product_edits/product.html.haml
admin/app/views/workarea/admin/inventory_skus/_cards.html.haml
admin/app/views/workarea/admin/inventory_skus/index.html.haml
admin/config/locales/en.yml
admin/test/integration/workarea/admin/jump_to_integration_test.rb
core/app/models/workarea/search/admin/inventory_sku.rb
core/config/locales/en.yml

Update admin views for consistent display of inventory availability

---

docs/data/articles.yml
docs/source/articles/cookies.html.md

Add document to describe cookie usage

---

core/app/models/workarea/shipping/service.rb
core/config/initializers/00_configuration.rb
core/test/models/workarea/shipping/service_test.rb

Add config to allow defining a default tax code for shipping services

---

core/config/initializers/00_configuration.rb

Allow blank on default shipping tax code

---

core/app/models/workarea/navigation/taxon.rb
core/app/models/workarea/sitemap.rb
core/app/models/workarea/sitemap/link.rb
core/app/queries/workarea/taxonomy_sitemap.rb
core/app/workers/workarea/generate_sitemaps.rb
core/config/initializers/05_scheduled_jobs.rb
core/config/initializers/07_dragonfly.rb
core/config/initializers/27_sitemaps.rb
core/lib/workarea/asset_endpoints/sitemaps.rb
core/lib/workarea/core.rb
core/test/models/workarea/navigation/taxon_test.rb
core/test/models/workarea/sitemap/link_test.rb
core/test/queries/workarea/taxonomy_sitemap_test.rb
core/test/workers/workarea/generate_sitemaps_test.rb
core/workarea-core.gemspec
storefront/app/views/workarea/storefront/pages/robots.text.erb
storefront/config/routes.rb
storefront/test/integration/workarea/storefront/sitemaps_integration_test.rb

Add sitemap generation

---

admin/app/views/workarea/admin/navigation_menus/_summary.html.haml

This will raise if the menu content is nil.

Fix safe navigation method calls

---

core/config/initializers/00_configuration.rb
core/lib/workarea/configuration/administrable/field.rb
core/test/lib/workarea/configuration/administrable/definition_test.rb
core/test/lib/workarea/configuration/administrable/field_test.rb
core/test/lib/workarea/configuration/administrable/fieldset_test.rb
core/test/models/workarea/configuration/params_test.rb

Make required true by default for admin config DSL

---

admin/config/locales/en.yml

There has been repeated confusion around why/how to use synonyms, so this is an attempt to clarify.

Try to clarify how to use search synonyms

---

admin/app/assets/stylesheets/workarea/admin/settings/_grid.scss
admin/app/views/workarea/admin/search_settings/show.html.haml
admin/config/locales/en.yml

This UI really needed a little TLC.

Clean up search settings UI

---

core/app/models/workarea/configuration/params.rb
core/config/initializers/00_configuration.rb
core/lib/workarea/configuration/administrable/field.rb
core/test/lib/workarea/configuration/administrable/field_test.rb
core/test/models/workarea/configuration/params_test.rb

Allow admin config array fields to define a values type

---

admin/app/helpers/workarea/admin/changesets_helper.rb
admin/app/view_models/workarea/admin/changeset_summary_view_model.rb
admin/app/view_models/workarea/admin/release_view_model.rb
admin/app/views/workarea/admin/changesets/index.html.haml
admin/app/views/workarea/admin/releases/_cards.html.haml
admin/config/locales/en.yml
admin/test/helpers/workarea/admin/changesets_helper_test.rb
admin/test/system/workarea/admin/releases_system_test.rb
core/app/models/workarea/release/changeset.rb
core/app/models/workarea/search/admin/releasable.rb
core/test/models/workarea/release/changeset_test.rb
core/test/models/workarea/search/admin/releasable_test.rb

Update display of release changeset to handle large changesets

---

core/config/initializers/00_configuration.rb

Do not require white/blacklist IP address admin config fields

---

admin/app/controllers/workarea/admin/create_release_undos_controller.rb
admin/test/integration/workarea/admin/create_release_undos_integration_test.rb

Fix building undos for changesets with missing releasable

---

docs/source/articles/system-emails.html.md

Add documentation for config.send_transactional_emails

---

admin/app/views/layouts/workarea/admin/application.html.haml
admin/test/integration/workarea/admin/direct_uploads_integration_test.rb
core/app/helpers/workarea/i18n_helper.rb

This API changed in the Rails 6 upgrade.
No changelog

Fix locale display in admin
