workarea-commerce/workarea

core/app/models/workarea/pricing/override.rb, core/test/models/workarea/pricing/override_test.rb
Workarea's default values for the Money fields in `Pricing::Override`
didn't previously change currency when `Money.default_currency` is
re-configured in process (like in the case of a multi-site application
with multiple currencies). Ensure that the correct currency is used by
using an Integer type as the default, which will get converted into a
Money type at runtime.
=> Fix Incorrect Currency in Mongoid Money Types

core/app/queries/workarea/search/storefront_search/exact_matches.rb, core/test/queries/workarea/search/storefront_search_test.rb
It's currently possible to customize search queries that return an exact
match, but instead of seeing the customized results when you run the
query, you'll be redirected to the product page since the
`StorefrontSearch::ExactMatches` middleware stops further middleware
execution and sets a redirect to the product path. To resolve the issue,
Workarea will now ignore this middleware if a customization is present
on the search response.
Discovered by **Ryan Tulino** of **Syatt Media**. Thanks Ryan!
ECOMMERCE-7063
=> Customize Search Queries That Return an Exact Match

admin/app/controllers/workarea/admin/content_assets_controller.rb, admin/app/controllers/workarea/admin/direct_uploads_controller.rb, core/app/services/workarea/direct_upload.rb, core/test/services/workarea/direct_upload_test.rb
Direct uploads can fail locally if your `Workarea.config.host` is not
set to the domain you are currently using in the browser. To prevent
this, instead of reading from the configuration when ensuring CORS
headers on the S3 bucket, use the `ActionDispatch::Request` from the
controller to determine the correct URL for CORS in this instance.
Addresses a problem whereby changing the domain (either accidentally or
on-purpose) causes direct uploads to fail, since it can't create the
proper CORS headers needed to transmit files into the bucket directly.
Fixes #19
=> Use Current Host For Direct Upload CORS Headers

core/lib/workarea/configuration/mongoid.rb
=> Use the same Mongo connection options for the index enforcement warning.

core/app/controllers/workarea/authentication.rb, core/app/controllers/workarea/impersonation.rb, storefront/test/integration/workarea/storefront/current_checkout_integration_test.rb
This got introduced as part of the changes for ECOMMERCE-7041.
No changelog
Discovered by me trying to get the wish lists v3.5 updates done.
=> Fix session resets and clearing current order when calling require_login

README.md, admin/app/views/workarea/admin/configurations/types/_array.html.haml, admin/app/views/workarea/admin/configurations/types/_duration.html.haml, admin/app/views/workarea/admin/configurations/types/_encrypted.html.haml, admin/app/views/workarea/admin/configurations/types/_float.html.haml, admin/app/views/workarea/admin/configurations/types/_integer.html.haml, admin/app/views/workarea/admin/configurations/types/_select.html.haml, admin/app/views/workarea/admin/configurations/types/_string.html.haml, admin/app/views/workarea/admin/configurations/types/_symbol.html.haml, core/app/models/workarea/configuration/params.rb, core/config/initializers/00_configuration.rb, core/lib/workarea/configuration.rb, core/lib/workarea/configuration/administrable/field.rb, core/test/lib/workarea/configuration/administrable/field_test.rb, core/test/models/workarea/configuration/params_test.rb, docs/source/articles/configuration-fields.html.md
* Add `allow_blank` option to field
* Require a value on fields that do not `allow_blank`
* Set field to default value if submitted blank when `allow_blank` is 
`false`.
* Remove `search_facet_default_sort` as admin configuration field to 
prevent confusion.
=> Update admin configuration options

storefront/test/system/workarea/storefront/products_system_test.rb
fixes #42
I cannot confirm, but my suspicion is that recently viewed may be the culprit here. I've adjusted the test to only look at the product details specifically.
=> Ensure test only asserts product details for product system test

admin/app/views/workarea/admin/comments/index.html.haml, admin/test/integration/workarea/admin/comments_integration_test.rb
Comments generated in plugins don't have an author; update the view to
handle rendering when the `author_id` is nil.
=> Fix showing comments without authors in admin

docs/Gemfile
Middleman was outdated, thus producing Security Vulnerability chatter.
@mttdffy was also blocked on #29 because of `middleman-search`'s
dependency on The Ruby Racer. We are now pointing to the
`workarea-commerce/middleman-search` fork which replaces The Ruby Racer
with Mini Racer.
Closes #28
=> Upgrade Middleman & Drop The Ruby Racer

plugin_template.rb
* Updates usage documentation at top of template
* Properly namespace directories under `app/assets`
* Set starting version to `1.0.0.pre`
* Point to HTTPS GitHub url instead of SSH
* Clean up generated README
* Add LICENSE
* Link license in gemspec and README
* Fix indentation and whitespace issues in gemspec
* Remove `script/` directory
* Clean up generated gitignore
* Fix link to developer documentation in README
* Fix flagrant quote fail for required Rails engines
Closes #25
=> Improve plugin template

admin/app/view_models/workarea/admin/product_view_model.rb, admin/test/integration/workarea/admin/products_integration_test.rb, admin/test/view_models/workarea/admin/product_view_model_test.rb
`ProductViewModel#default_category` now protects against a `nil` value
for the default category before passing its value into a view model.
My first approach was to try and change `ApplicationViewModel.wrap` to protect against `nil` values across the board, but this broke some stuff in `ShippingCarrierViewModel`, which depends on `model` being able to be `nil` and kinda acts as a null object...
Fixes #33
=> Fix Wrapping `nil` Values in Product View Model

docs/source/articles/products.html.md.erb, docs/source/articles/testing.html.md, docs/source/articles/workers.html.md
* Storefront price partial removed
* `Workarea.with_config` obsoleted by automatic resetting
of configuration between tests
* Changes to headless Chrome configuration
* Changes to Sidekiq queues
* Addition of `query_cache` Sidekiq option
=> Update docs to reflect changes in Workarea 3.5

storefront/app/views/workarea/storefront/checkouts/confirmation.html.haml
Adds additional append point to the order confirmation page view underneath default order confirmation text.
=> Add order confirmation append point

admin/app/assets/javascripts/workarea/admin/application.js.erb, admin/app/views/workarea/admin/orders/attributes.html.haml, admin/config/locales/en.yml, admin/test/system/workarea/admin/orders_system_test.rb, core/app/assets/javascripts/workarea/core/modules/copy_to_clipboard.js, core/config/locales/en.yml
Due to the length of URLs being displayed on Order Attributes in the admin
they will potentially break layout. Now they are displayed within a tooltip
behind a "View" link click. The resulting tooltip will prompt the user to
copy the contents of a text box containing the URL.
Fixes #60
=> Display Referrer URL in tooltip on Order Attributes in Admin

testing/lib/workarea/system_test.rb
Chrome automatically logs unsuccessful (4xx or 5xx) responses to the
console. Once `Capybara::Chromedriver::Logger` was installed to
output the logs from the console into the test results, 401/422
responses on `/current_user.json` and `/login` caused error messages to
appear in tests. These responses are expected, however, since the system
tests that threw the errors are actually testing what happens when a
login fails or an admin needs to reset their password. To silence these
warnings, Workarea added a regex filter to omit any console logs for
unauthorized `/current_user.json` requests and bad `/login` attempts.
Fixes #90
=> Add Chromedriver Logger Filter for Expected Errors

storefront/app/views/workarea/storefront/pages/robots.text.erb
This was a relic from a more monolithic age and will be readded by
workarea-commerce/workarea-wish-lists#2.
Closes #106
=> Remove /wish_lists entry from Robots.txt

storefront/app/views/layouts/workarea/storefront/checkout.html.haml, storefront/app/views/workarea/storefront/cart_items/create.html.haml, storefront/app/views/workarea/storefront/carts/show.html.haml, storefront/app/views/workarea/storefront/orders/_summary.html.haml, storefront/app/views/workarea/storefront/orders/show.html.haml, storefront/app/views/workarea/storefront/recommendations/show.html.haml, storefront/app/views/workarea/storefront/searches/show.html.haml, storefront/app/views/workarea/storefront/users/accounts/edit.html.haml, storefront/app/views/workarea/storefront/users/accounts/show.html.haml, storefront/app/views/workarea/storefront/users/addresses/edit.html.haml, storefront/app/views/workarea/storefront/users/addresses/new.html.haml, storefront/app/views/workarea/storefront/users/credit_cards/edit.html.haml, storefront/app/views/workarea/storefront/users/credit_cards/new.html.haml, storefront/app/views/workarea/storefront/users/orders/index.html.haml, storefront/app/views/workarea/storefront/users/orders/show.html.haml, storefront/app/views/workarea/storefront/users/passwords/new.html.haml
There seems to be little reason to bloat the markup of pages explicitly
disallowed in our default `robots.txt` file.
Closes #82
=> Remove Schema.org structured data from unspiderable pages

core/lib/workarea/ext/freedom_patches/mongoid_simple_tags.rb, core/test/lib/workarea/ext/freedom_patches/mongoid_simple_tags_test.rb
When inserting tags into a taggable document, make sure their values are
unique. This addresses an issue where incorrect tag counts were being
displayed on the storefront.
I couldn't use a `Set` for this, even though Mongoid allows for it, because we have a lot of instances throughout our app (and I assume the greater Workarea community) of tests that assert that `.tags` is equal to an Array of some kind. Using `Set` would have required one to append `.to_set` onto the expected value of those assertions, so we're just calling `.uniq` when tags are set on a given model.
Fixes #112
=> Ensure Tags Are Unique

docs/source/upgrade-guides/workarea-3-4-0.html.md
In the upgrade guide for v3.4, we're instructing users to apply an app
template which no longer exists. Instead of using the app template, we
now rely on a generator called `workarea:install` to place the expected
files into your Rails app directory, so update the command in docs to
avoid confusion.
=> Replace App Template Command With Install Generator in Upgrade Docs

core/app/models/workarea/catalog/product_image.rb, core/test/models/workarea/catalog/product_image_test.rb
Populate the `:image_inverse_aspect_ratio` automatically using
Dragonfly, in order to reduce the amount of requests made to S3 in order
to find out this information. This way, Dragonfly can store more assets
in the cache.
(#116)
=> Add Inverse Aspect Ratio To Product Image Fields

core/lib/workarea/routes_constraints/super_admin.rb
The RoutingConstraints::SuperAdmin protects access to the Sidekiq
web interface. The constraint needed to be updated to reflect the
storing of user_id in session as of v3.5
=> Check session for user_id over cookies

core/lib/workarea/configuration.rb, core/test/models/workarea/payment/credit_card_integration_test.rb
Since we're no longer able to regenerate VCR cassettes at-will (due to
credentials needing to be scrubbed before pushing to GitHub), this
configuration setting is no longer necessary, and furthermore, could
potentially prevent legitimate tests from running and catching bugs in
the wild. Remove the configuration and the guard clause in the refund
tests for `Workarea::Payment::CreditCardIntegrationTest`, and fix any
build failures in plugins as they come up.
=> Remove Refund Tests

storefront/test/system/workarea/storefront/release_browsing_system_test.rb
This test has started failing due to Capybara or Selenium not finding
the release select in the iframe. A simple sleep fixes the problem, we
weren't able to track down a proper cause.
We'll be refactoring the admin toolbar away from an iframe in v3.6, so
this will be a temporary hack to fix. We'll remove this at that point in
time.
=> Fix test failure due to iframe loading

storefront/app/controllers/workarea/storefront/recent_views_controller.rb, storefront/app/view_models/workarea/storefront/user_activity_view_model.rb, storefront/test/integration/workarea/storefront/recent_views_integration_test.rb, storefront/test/view_models/workarea/storefront/user_activity_view_model_test.rb
This was an oversight that got caught and fixed in the `flow-io` plugin,
but should really be in base since it will allow more control over the
product summaries on the recent views action. The `view_model_options`
were not getting passed into the `UserActivityViewModel`, and thus the
`ProductViewModel` instances that it creates, causing some stale content
to appear in the view.
=> Pass Options To `Storefront::UserActivityViewModel`

admin/app/view_models/workarea/admin/timeline_view_model.rb, admin/app/views/workarea/admin/timeline/show.html.haml, admin/config/locales/en.yml, admin/test/view_models/workarea/admin/timeline_view_model_test.rb
The Timeline UI should now display:
1. Unscheduled changesets
1. Scheduled changesets, ordered by the release's publish date,
descending
1. Today (if applicable)
1. Historical changesets
=> Improve order of changesets in Timeline UI (#124)

admin/app/views/workarea/admin/content_assets/_summary.html.haml, admin/app/views/workarea/admin/content_assets/index.html.haml, admin/app/views/workarea/admin/content_blocks/_asset.html.haml, admin/config/locales/en.yml, core/config/initializers/14_content_block_types.rb
In an effort to make the recent updates to alt text overridding in
Content Blocks a bit clearer, alt text is now being output:
- On the content assets index view
- In the title for a content asset summary
Default alt text has been removed from the Content block DSL, which
makes the default text come directly from the Asset itself.
The help text displayed on Asset Content Blocks always appears now,
better explaining the behavior of this feature.
=> Surface Asset alt text and behavior within Content Blocks (#95)

admin/app/controllers/workarea/admin/catalog_categories_controller.rb, admin/app/views/workarea/admin/product_rules/fields/_category.html.haml, admin/config/locales/en.yml, admin/test/integration/workarea/admin/categories_integration_test.rb
Adding the same ID to a category product rule matching the product list
that contains it results in some wonky results coming back. This was
originally diagnosed as an issue when combining category rules, but in
reality, it has to do with an admin mis-using the product rules
interface and perhaps accidentally using the category's own ID in a
product rule. To prevent this from happening, clean the
`product_list.id` from the value if a category rule is created or
updated.
Fixes #52
=> Fix Self-Referential Category Rules

core/app/middleware/workarea/tracking_middleware.rb, core/app/models/workarea/segment.rb, core/lib/workarea/cache.rb, core/lib/workarea/configuration/session.rb, core/lib/workarea/ext/freedom_patches/string.rb, core/lib/workarea/visit.rb
These changes reduce allocations by about 18% on cached pages.
No changelog
Results here: https://github.com/workarea-commerce/workarea/pull/new/object-allocation-improvments
=> Reduce object allocations (focused on Rack cached requests)

core/app/models/workarea/catalog/customizations.rb, core/test/models/workarea/catalog/customizations_test.rb
When adding a customized field to a `Customizations` class that ends in
`_id`, Workarea was previously stripping this suffix from the computed
instance variable name that is converted into snake case from any kind
of input. This causes issues because the data doesn't appear to be
making it into customizations, but is really there under a different
instance variable name. To resolve the issue, Workarea now detects
whether a variable is already using snake case and leaves it
alone...only providing transformations for variable names that need it.
(#144)
=> `_id` Suffix Omitted From Customized Fields

core/app/models/workarea/navigation/breadcrumbs.rb, core/test/models/workarea/navigation/breadcrumbs_test.rb, storefront/app/view_models/workarea/storefront/product_view_model.rb, storefront/test/helpers/workarea/storefront/navigation_helper_test.rb, storefront/test/helpers/workarea/storefront/schema_org_helper_test.rb
The `storefront_url_for` method doesn't handle models other than taxons,
but the Schema.org helpers use it to render breadcrumb URLs in the
`BreadcrumbList` for any model that's in the breadcrumbs. To prevent
incorrect URLs from showing up in the breadcrumbs, the
`Navigation::Breadcrumbs` class has been modified to accept a model
object as its `:last` parameter, instead of just a name, to be added to
an arbitrary `Navigation::Taxon` created for the purpose of rendering
both the name and URL of the final navigation taxon. This wasn't needed
prior to the introduction of Schema.org's `BreadcrumbList`, because the
final URL of breadcrumbs was always left out. The helper methods that
render the breadcrumbs will continue to leave out the final taxon's URL,
but for breadcrumbs in Schema.org, the …
=> Fix Product URL In Breadcrumbs

core/workarea-core.gemspec
Sprockets v4.0 was released on 10/8/2019, which removed the
`.register_engine` method that is depended on by many extensions to
Sprockets at the current moment. Lock down Sprockets to v3.7.2 to avoid
these issues, which will show up when the app is loaded or tests are
run.
WORKAREA-18
=> Lock Down Sprockets to v3.7.2

core/app/controllers/workarea/current_segments.rb, core/app/controllers/workarea/current_tracking.rb, storefront/test/integration/workarea/storefront/segments_integration_test.rb
Requests for asset-type file formats can cause errors if they can't be
found.
No changelog
=> Fix errors on requests without visits

admin/app/controllers/workarea/admin/pricing_overrides_controller.rb, admin/app/helpers/workarea/admin/pricing_overrides_helper.rb, admin/app/views/workarea/admin/users/permissions.html.haml, admin/test/integration/workarea/admin/pricing_overrides_integration_test.rb, core/app/controllers/workarea/authorization.rb, core/app/models/workarea/user/authorization.rb, core/lib/workarea/configuration.rb, core/test/integration/workarea/authorization_test.rb, storefront/test/system/workarea/storefront/pricing_overrides_system_test.rb
I ran across this and it was bugging me again. Renamed to match non-admin-area based permissions.
Also allows authorization based on non-access-suffxed methods.
=> Rename order management permissions

docs/source/articles/system-emails.html.md
Direct readers to ActionMailer resources when they're looking to create
new mailers rather than style or modify existing ones. Also added some
information about unit testing mailer classes.
=> Improve Mailer Documentation

core/app/models/workarea/catalog/product_image.rb, core/app/models/workarea/catalog/product_placeholder_image.rb
This magic attribute doesn't need to be calculated, it's the inverse of the aspect ratio we already have.
=> Fix missing aspect ratio magic attribute

storefront/test/system/workarea/storefront/analytics_system_test.rb, testing/lib/workarea/storefront/system_test.rb
Adds clarity, as "events" is a little ambiguous to server or browser.
No changelog
=> Rename analytics test helper

admin/app/view_models/workarea/admin/changeset_view_model.rb, admin/test/view_models/workarea/admin/changeset_view_model_test.rb
Can raise an error when rendering changesets on the release's show page.
=> Fix changeset loading missing root

core/app/models/workarea/search/storefront.rb, core/app/models/workarea/segment.rb, core/app/models/workarea/segmentable.rb, core/test/models/workarea/segmentable_test.rb
In most situations, you actually don't want segmenting enabled. For
example, the admin, the API, when search indexing, etc.
This disables segments unless they are specifically enabled. Right now,
the only place that would be is in the storefront.
No changelog
=> Disable segmenting activeness unless specifically enabled

core/app/models/workarea/catalog/product.rb
Plugins like package products need a place to add more logic to a
product's activeness without having to reimplement all of active's
`super`. With the addition of segments, this becomes a bunch of
code.
I'll be opening another PR to implement this change in package products to fix the mega build failure here: https://github.com/workarea-commerce/mega-build/runs/271831151#step:4:1452
=> Add a hook method to allow extending product's activeness

core/app/models/workarea/content.rb, core/app/models/workarea/content/block_type_definition.rb
Allow autoloading to function properly, even though it can cause some
problems. This will be a more graceful upgrade experience.
No changelog
=> Fix completely breaking content block definition

admin/app/helpers/workarea/admin/application_helper.rb, admin/app/views/workarea/admin/catalog_products/index.html.haml, admin/app/views/workarea/admin/content_assets/index.html.haml, core/lib/workarea/configuration.rb, docs/source/upgrade-guides/workarea-3-5-0.html.md
This causes problems spinning up environments in other hosting setups
where S3 isn't available or desired.
To retain the old behavior (which you'll want if you're on the Workarea
Commerce Cloud) drop this into an initializer:
`Workarea.config.asset_store = (Rails.env.test? || Rails.env.development?) ?
:file_system : :s3`
WORKAREA-32
=> Don't default to S3 asset store

core/lib/tasks/services.rake
This can cause problems if bundler outputs warnings/errors. There's a safe way to do it in Ruby, so use that instead.
Fixes #191
=> Don't shell out to bundler to get gem path

core/test/models/workarea/pricing/calculators/tax_calculator_test.rb
The `Pricing::Calculators::Calculator.test_adjust` method accepts two
arguments, and expects the first argument is going to be of type
`Order`, but in a `TaxCalculator` test only a shipping was being passed
in. Update this test to use the correct syntax so that other downstream
projects that expect data to be on an Order won't get confused.
=> Fix Incorrect Test Setup

admin/app/view_models/workarea/admin/content_view_model.rb, admin/test/view_models/workarea/admin/content_view_model_test.rb, core/app/models/workarea/content/asset.rb, storefront/app/view_models/workarea/storefront/display_content.rb, storefront/test/view_models/workarea/storefront/display_content_test.rb
=> Allow an asset to be tagged 'og-default' to use for open graph images

admin/app/assets/javascripts/workarea/admin/modules/timeline_report_chart.js, admin/app/view_models/workarea/admin/reports/timeline_view_model.rb, admin/test/view_models/workarea/admin/reports/timeline_view_model_test.rb
* Datasets contain points for every day
* Releases show regardless of other data in dataset
* Display dates in UTC, fixing date offset issue
* Re-align tooltip when hovering over Release datapoint
WORKAREA-31
=> Clean up Timeline Report Chart UI

core/workarea-core.gemspec
If we remove this restriction, we can use newer versions of the `mongo` gem, which contain cluster fixes.
=> Remove now-unneeded version restriction on the BSON gem

core/app/models/workarea/metrics/affinity.rb, core/app/models/workarea/metrics/user.rb, core/app/queries/workarea/recommendation/user_activity_based.rb, core/lib/workarea/configuration.rb, core/test/models/workarea/metrics/affinity_test.rb, core/test/models/workarea/metrics/user_test.rb, storefront/app/view_models/workarea/storefront/user_activity_view_model.rb
This will allow us to do better segmenting in the future with rules like
"viewed this product more than once".
WORKAREA-88
=> Allow storing non-unique recently viewed items

core/app/workers/workarea/synchronize_user_metrics.rb, core/lib/tasks/migrate.rake
=> Ensure a user's metrics admin status is always kept in sync

core/app/models/workarea/metrics/search_by_day.rb
I noticed in one of our projects, SearchCustomizations and SearchSettings were slugging along. I discovered that SearchByDay was the root cause of the slowness/timeouts. SearchByWeek had the index so I think it may have just been an oversight. Let me know if it was intentionally left out.
=> Add index to SearchByDay model

core/workarea-core.gemspec
Fixes bundler-audit failures in builds.
=> Bump Chartkick dependency to fix security warning

core/workarea-core.gemspec
This new version requires `Rack::Cache` v1.10 and enables over-the-wire
gzip compression to the Redis server. This feature is useful for
extremely high traffic sites, but should be used with caution since it
will increase the CPU/RAM load on your application server. You should
use this if the trade-off between RAM increase and bandwidth decrease
makes sense.
WORKAREA-94
=> Update `Redis::Rack::Cache` to v2.2.0

docs/source/release-notes.html.md, docs/source/release-notes/workarea-3-0-66.html.md, docs/source/release-notes/workarea-3-0-67.html.md, docs/source/release-notes/workarea-3-1-53.html.md, docs/source/release-notes/workarea-3-1-54.html.md, docs/source/release-notes/workarea-3-2-42.html.md, docs/source/release-notes/workarea-3-2-43.html.md, docs/source/release-notes/workarea-3-3-35.html.md, docs/source/release-notes/workarea-3-4-21.html.md
Whooooo boy! Lots of releases here because apparently I forgot or was
not aware of us releasing earlier versions last week. Sorry about that.
Anyway, here are the release notes from those backlogged versions as
well as the ones we're actually releasing today. :)
=> Patch Release Notes for v3.0.66, v3.0.67, v3.1.53, v3.1.54, v3.2.42, v3.2.43, v3.3.34, v3.3.35, and v3.4.21

docs/source/javascripts/site.js
The table of contents that appears within each doc contains a link to
every h2-h6 in the document. Therefore, in longer docs, the TOC gets
quite crowded and stops communicating the overall structure of the doc.
Help readers maintain context by simplifying the TOC, limiting links to
h2-h3.
I spot-checked docs of various lengths and found this version of the TOC
more useful in all cases.
WORKAREA-96
=> Improve table of contents for docs

admin/app/views/workarea/admin/insights/_cold_searches.html.haml, admin/app/views/workarea/admin/insights/_hot_searches.html.haml, admin/app/views/workarea/admin/insights/_searches_to_improve.html.haml, admin/app/views/workarea/admin/insights/_star_searches.html.haml, admin/app/views/workarea/admin/insights/_trending_searches.html.haml, core/app/models/workarea/insights/trending_searches.rb, core/test/models/workarea/insights/cold_searches_test.rb, core/test/models/workarea/insights/hot_searches_test.rb, core/test/models/workarea/insights/searches_to_improve_test.rb, core/test/models/workarea/insights/star_searches_test.rb, core/test/models/workarea/insights/trending_searches_test.rb
Query string will also be used in the search autocomplete output.
=> Use query string over ID for insights display

docs/source/stylesheets/_typography.scss
The presentation of inline code (e.g. class names) within hyperlinks is
a bit jarring. Only recent docs are linking to code, so it is just now
appearing as an issue.
Adjust the styles for code within links to be more traditional.
WORKAREA-108
No changelog
=> Improve presentation of code within links

storefront/test/integration/workarea/storefront/checkout_side_effects_integration_test.rb, storefront/test/integration/workarea/storefront/checkouts_integration_test.rb, storefront/test/integration/workarea/storefront/impersonations_integration_test.rb, storefront/test/integration/workarea/storefront/order_data_integration_test.rb, storefront/test/integration/workarea/storefront/place_order_integration_test.rb, storefront/test/integration/workarea/storefront/placing_order_integration_test.rb, storefront/test/integration/workarea/storefront/store_credit_integration_test.rb, storefront/test/integration/workarea/storefront/users/credit_cards_integration_test.rb, testing/lib/workarea/testing/factories/payment.rb
The credit card expiration year `2020` was hard-coded into many Workarea
integration tests, and would fail when January 2020 passes. Update these
tests to always set the credit card expiration year to 3 years in
advance of when the test runs so this won't happen again in the future.
WORKAREA-104
Fixes #222
=> Update Tests Referencing 2020

core/lib/workarea/configuration.rb, core/test/models/workarea/data_file/csv_test.rb
UTF-8 doesn't need a BOM in order to start or end a file, but these
characters can end up in CSVs generated by older software that doesn't
have great support for Unicode. As a result, if a BOM is in the CSV near
`_id` it will cause improper importing of the data held within. To
address this, Workarea now specifies the `bom|` prefix in the `:encoding`
param for `CSV.foreach` by default. This can still be overridden if you
have an ASCII file, and since BOM stripping doesn't really apply,
developers can override the entire encoding string in configuration
if necessary. But this is a sane default for those who use UTF-8 and
happen to be exporting out of older spreadsheet software.
=> Import UTF-8 CSVs With BOM Characters

admin/app/controllers/workarea/admin/data_file_imports_controller.rb, admin/app/views/workarea/admin/data_file_imports/new.html.haml, admin/test/integration/workarea/admin/data_file_imports_integration_test.rb, core/app/models/workarea/data_file/operation.rb
This ensures data file import samples are always treated as UTF-8.
While Ruby itself does do this pretty well, and most browsers are good
at guessing the file type/encoding based on the contents of the file,
there might be some outliers that rely on metadata that's a bit more
strictly adhered to. This change ensures that sample CSV/JSON files are
delivered to the user as an attachment, and using the correct MIME type,
so that they register as such when downloaded by the browser.
Previously, all imports were showing as "TXT file" types, when they were
really "CSV file" or "JSON file", and at least in Firefox, they were not
downloading when you clicked the sample link. Instead, a new tab would
open (since Firefox thinks it's a text file), and you have to refresh
the page to actually get the …
=> Ensure UTF-8 Encoding of Data File Import Samples

admin/app/assets/javascripts/workarea/admin/config.js.erb, admin/app/assets/javascripts/workarea/admin/modules/timeline_report_chart.js, admin/app/assets/javascripts/workarea/admin/modules/tooltips.js, admin/app/view_models/workarea/admin/reports/timeline_view_model.rb, admin/app/views/workarea/admin/reports/timeline.html.haml, admin/test/view_models/workarea/admin/reports/timeline_view_model_test.rb
QA uncovered some weirdness, namely:
* Stop Orders from being active by default
* Stop bubbling of the events triggered from within the tooltip
* Order events by time when many are displayed within the same day
* Display Events in graph above other data sets
* Fix tooltip functionality browsers other than Chrome
No changelog
WORKAREA-86
=> Clean up Timeline Report Chart

admin/app/assets/javascripts/workarea/admin/modules/selects.js, admin/test/system/workarea/admin/content_system_test.rb
`WORKAREA.remoteSelects` works in a similar fashion where, to clear a
multiple-select Select2 instance we inject a hidden input before the
select menu in the DOM to be able to pass empty data along to the server
after the selection is made.
This is a little cleaner than Select2's default behavior, which forces
you to create a blank "placeholder" element, the value of which cannot
be an empty string. Weird, I know.
No changelog
WORKAREA-119
=> Inject a hidden input for Select2 instances that allowClear

core/app/queries/workarea/order_item_details.rb, core/lib/workarea/configuration.rb
This was a point of bottleneck during recent Reformation load-testing.
WORKAREA-102
=> Add caching to order item details results

docs/source/stylesheets/_typography.scss
Nested lists look awkward because whitespace is applied only to the
bottom of each list item, so there is no separation between the raw text
within a list item and the list that follows it.
Move list item margin from the bottom to the top to fix this issue.
There are no unwanted side effects at the top or bottom of each list,
because each ul/ol has its own top and bottom margin which is greater
than the margin applied to the li.
WORKAREA-127
=> Improve presentation of nested lists

.github/ISSUE_TEMPLATE/documentation-request.md, docs/config.rb, docs/source/layouts/article.erb
Documentation feedback is collected anonymously through a Google form.
This does not allow for communication with the reporter, and it is an
additional communication channel that has to be managed separately.
Use GitHub issues instead of the Google form to collect documentation
feedback. This allows triaging docs issues using the same process used
for the software and allows communication with the reporter (to thank
them, ask questions, provide a status, or help them if the issue is not
actually a documentation problem).
Also update the documentation issue template to broaden its scope and
provide a default assignee.
WORKAREA-64
No changelog
=> Improve documentation feedback process

core/config/initializers/00_configuration.rb, core/lib/workarea/configuration.rb
This causes a null value for expireAfterSeconds when creating indexes in
Mongo.
=> Fix password config not available when building indexes

admin/app/view_models/workarea/admin/dashboards/marketing_view_model.rb, core/app/models/workarea/insights/customer_acquisition.rb, core/app/models/workarea/insights/trending_products.rb, core/app/models/workarea/insights/trending_searches.rb, core/app/models/workarea/metrics/product_for_last_week.rb, core/app/models/workarea/metrics/search_for_last_week.rb, core/app/models/workarea/metrics/user.rb, core/app/queries/workarea/reports/average_order_value.rb, core/app/queries/workarea/reports/first_time_vs_returning_sales.rb, core/app/queries/workarea/reports/group_by_time.rb, core/app/queries/workarea/reports/sales_by_category.rb, core/app/queries/workarea/reports/sales_by_country.rb, core/app/queries/workarea/reports/sales_by_discount.rb, core/app/queries/workarea/reports/sales_by_menu.rb, core/app/queries/workarea/reports/sales_by_product.rb, core/app/queries/workarea/reports/sales_by_sku.rb, core/app/queries/workarea/reports/sales_by_traffic_referrer.rb, core/app/queries/workarea/reports/sales_over_time.rb, core/app/queries/workarea/reports/searches.rb, core/app/queries/workarea/reports/searches_over_time.rb, core/app/queries/workarea/reports/searches_without_results_over_time.rb
This build shows it passing with Sydney set to the timezone: https://github.com/workarea-commerce/workarea/commit/8553cd6e06a09539869968ea4bb9dc1596e44493/checks?check_suite_id=349971418
Fixes #278
=> Fix time zone querying for insights and reports

core/lib/workarea/configuration/redis.rb, core/test/lib/workarea/configuration/redis_test.rb
This makes Redis configuration a little more robust, allowing partial
configuration values that will always end up falling back to defaults.
=> Improve Redis configuration defaulting

README.md
Based on feedback from Lou Perseghin, I wanted to make it clear that in order to install Workarea locally, you need to install Docker, and that the command you're running is being run in terminal.
=> Slightly more specific language

core/app/models/workarea/data_file/csv.rb, core/app/models/workarea/data_file/json.rb, core/test/models/workarea/data_file/csv_test.rb, core/test/models/workarea/data_file/json_test.rb
Update the `:updated_at` timestamp to the current time when existing
models are updated via an import, and ignore any settings of the
`:updated_at` timestamp in JSON/CSV imports, as this can interfere with
cache key generation.
=> Exclude Update Timestamp From Imports

.github/actions/build_documentation/Dockerfile, .github/actions/build_documentation/documentation/Gemfile, .github/actions/build_documentation/documentation/build.rb
No changelog
Original error: https://github.com/workarea-commerce/workarea/commit/c84f52e921a22e4dd52b1fe3fa124293cd824715/checks?check_suite_id=362715601#step:3:233
=> Fix bundle gems not found when building docs

docs/source/release-notes/workarea-3-4-23.html.md, docs/source/release-notes/workarea-3-5-1.html.md
A small linking error here, no big deal.
=> Fix Typo in Release Notes

core/lib/tasks/tests.rake
Instead of using a Boolean `true` value, use the String `"true"` so Ruby
won't complain when running the task. Noticed this when creating the API
docs task.
=> Fix Performance Test Task

.github/workflows/ci.yml
Run tests and static analysis when workflow files change, this will help
when testing workflows in the future.
**NOTE:** This is being PRed into `v3.5-stable` because `v3.4-stable`
doesn't have any of the `:paths-ignores` rules set up, so it's not
affected.
=> Trigger CI When Workflow Configs Change

core/app/controllers/workarea/current_tracking.rb, core/app/middleware/workarea/application_middleware.rb, core/lib/tasks/migrate.rake, core/workarea-core.gemspec, storefront/test/integration/workarea/storefront/analytics_integration_test.rb
A few bonus fixes in here, check the commits if you're interested.
Here's the summary:
Rack >= 2.0.8 adds the idea private/public session IDs to prevent timing
attacks where a session ID can be stolen. This is big for sessions stored
in databases because the session can then be stolen.
Workarea only supports a cookie session store, so we can continue to
safely use the cookie value of the session ID for metrics lookups.
You can learn more about the Rack vulnerability here:
GHSA-hrqr-hxpp-chr3
=> Fix session ID use for latest rack

docs/source/articles/add-a-content-area.html.md, docs/source/articles/add-a-content-block-type.html.md, docs/source/articles/appending.html.md, docs/source/articles/configuration.html.md, docs/source/articles/error-pages.html.md.erb, docs/source/articles/extension-overview.html.md, docs/source/articles/overriding.html.md, docs/source/articles/testing.html.md
The current publishing system does not support footnotes, so find the
remaining footnotes and update them.
Remove those of questionable value and "inline" the others as
parentheticals where they are referenced.
WORKAREA-137
(No changelog)
=> Inline remaining footnotes

docs/source/articles/b2b-overview.html.md, docs/source/articles/integrate-an-inventory-management-system.html.md, docs/source/articles/order-life-cycle.html.md, docs/source/articles/order-pricing.html.md, docs/source/articles/overriding.html.md, docs/source/articles/searching.html.md, docs/source/articles/themes-overview.html.md, docs/source/upgrade-guides.html.md, docs/source/upgrade-guides/workarea-3-4-0.html.md, docs/source/upgrade-guides/workarea-3-5-0.html.md
Stash repositories were moved to GitHub.
Update links to public repositories, and remove links to private
repositories.
WORKAREA-136
(No changelog)
---
Homebase pages are not accessible to all Workarea users.
Update or remove links to Homebase, substituting public GitHub
links where possible.
WORKAREA-136
(No changelog)
=> Update Stash and Homebase links

docs/source/articles/infrastructure.html.md
No one outside the Workarea Commerce organization can view this repository,
so it doesn't make sense to link to it from the docs.
A user understandably thought the link was broken (#298) because it
resulted in a 404.
Remove the link to avoid further confusion.
WORKAREA-157
(No changelog)
=> Remove link to private repository

core/workarea-core.gemspec
The new version of bundler can not seem to correctly use wysihtml-rails version 0.6.x. Setting the version to 0.6.0.beta2 fixes the dependency issues.
no changelog
=> Update wysihtml-rails version

Rakefile, plugin_template.rb
We're running out of minutes in our GitHub actions due to duplicate pushes
during a release. This consolidates the two pushes into one.
The plugin template is also updated to ensure new plugins don't suffer
from the same issue in the future.
No changelog
WORKAREA-148
=> Remove extraneous push in Release task

admin/test/system/workarea/admin/impersonation_system_test.rb, storefront/test/system/workarea/storefront/release_browsing_system_test.rb, storefront/test/system/workarea/storefront/segment_overrides_system_test.rb, testing/lib/workarea/system_test.rb
synchronize sleeps in 0.01 increments up to the default_wait_time of Capybara.  The find_button triggers its own synchronize but I think there is a bug that causes a loss of context of the within_frame, the outer synchronize seems to solve this
=> Remove wait_for_iframe

admin/app/helpers/workarea/admin/content_helper.rb, admin/app/views/layouts/workarea/admin/application.html.haml
We need to be more permissive in our linking to footer content areas
from the header, since themes and builds can technically rename these
areas. Now this link will point to the first content area that contains
the word 'footer'.
WORKAREA-145
=> Link to first "footer" area in layout Content from Shortcuts

admin/app/views/workarea/admin/orders/attributes.html.haml
This adds an append point right underneath the order subtotal and above
the shipping total in the admin order attributes view.
=> Add Append Point For Post Subtotal Adjustments

core/lib/workarea/configuration.rb
So we can ensure the product has the intended pricing when published.
No changelog
=> Publish pricing with a release before the product

core/app/models/workarea/segmentable.rb
This will fix errors raised when `active_segment_ids` are `nil`.
=> Fix nil segment IDs

admin/app/assets/javascripts/workarea/admin/application.js.erb, admin/app/assets/javascripts/workarea/admin/modules/copy_ids.js, admin/app/assets/javascripts/workarea/admin/modules/product_copy_ids.js, admin/app/controllers/workarea/admin/catalog_product_copies_controller.rb, admin/app/controllers/workarea/admin/content_page_copies_controller.rb, admin/app/helpers/workarea/admin/content_helper.rb, admin/app/views/workarea/admin/catalog_product_copies/new.html.haml, admin/app/views/workarea/admin/catalog_products/show.html.haml, admin/app/views/workarea/admin/content_page_copies/new.html.haml, admin/app/views/workarea/admin/content_pages/show.html.haml, admin/app/views/workarea/admin/create_content_pages/setup.html.haml, admin/config/locales/en.yml, admin/config/routes.rb, admin/test/integration/workarea/admin/catalog_product_copies_integration_test.rb, admin/test/integration/workarea/admin/content_page_copies_integration_test.rb, admin/test/system/workarea/admin/page_copy_system_test.rb, core/app/models/workarea/content/page.rb, core/app/services/workarea/copy_page.rb, core/lib/workarea/configuration.rb
Modeling Product copying, Page copying allows for a page and its content
to be cloned and worked on as a separate page.
A deprecation warning has been added to `WORKAREA.productCopyIds` as
this module was too specific to copying products. The new, generalized
`WORKAREA.copyIds` should be used instead.
WORKAREA-168
=> Add Page copying to Admin

core/app/workers/sidekiq/callbacks.rb, core/app/workers/sidekiq/callbacks_worker.rb, testing/lib/workarea/test_case.rb
This can cause missing workers in development, which causes callback
workers which should be enqueued to be missing.
I have no idea how to write a test for this.
=> Fix Sidekiq callbacks workers missing due to code reloaded

docs/source/javascripts/site.js, docs/source/search.html.erb, docs/source/stylesheets/_components.scss
Improve the "no search results" UI to encourage users to open a GitHub
issue explaining what documentation they aren't able to find.
WORKAREA-177
=> Add feedback mechanism to empty search results

admin/app/assets/javascripts/workarea/admin/modules/content_block_list.js, admin/app/assets/javascripts/workarea/admin/modules/content_blocks.js, admin/test/system/workarea/admin/content_system_test.rb
How many times have you gone to edit a content block that's wayyy low in
your content page only to have the page scroll all the way back up to
the top of the page after saving? Two? Three? 500 or more times?
Well, scroll no more, with this new improvement that retains your scroll
position!
WORKAREA-172
=> Preserve scroll position after content block save

docs/source/articles/create-a-new-app.html.md
The procedure in "Create a New Workarea App" fails at step 3:
"Install Workarea into the Rails application", because that step
requires MongoDB to be running.
Fix the procedure by transposing steps 3 and 4, resulting in
"Start Workarea service dependencies" running before "Install Workarea
into the Rails application", which ensures MongoDB is available.
I re-tested the entire procedure from scratch to ensure this works.
WORKAREA-186
=> Fix order of steps to create new app

docs/source/articles/add-a-fraud-analyzer.html.md
The doc "Add a Fraud Analyzer" contains an incomplete sentence
describing the embedded `FraudDecision` document.
Re-write the sentence to complete the thought and to link to the
definition of the `FraudDecision` model.
WORKAREA-176
=> Fix incomplete sentence in "Add a Fraud Analyzer"

docs/source/articles/configuration.html.md
The "Configuration" doc has a section that covers changing configuration
within tests. The section hasn't been updated for Workarea 3.5.
Rather than update the content in-place, replace this coverage with a
reference to the up-to-date coverage of this topic within the "Testing"
section of the documentation.
WORKAREA-175
=> Update testing coverage in "Configuration"

core/workarea-core.gemspec
If one installs Workarea when running Ruby 2.4.x and below, a test will
fail because it is expecting that `#casecmp?` will be able to handle
`nil` arguments without throwing a `TypeError`. To address this,
`Workarea::Core` now restricts the required Ruby version in the gem
specification to 2.5.0 and above, dropping support for 2.4 and below,
which at this point is also reaching EOL by the Ruby maintainers.
=> Drop Support for Ruby 2.4 and Below

admin/app/views/workarea/admin/navigation_menus/index.html.haml
Noticed this while setting up the primary navigation.
=> Use correct page title for navigation menus index

docs/data/articles.yml, docs/source/articles/install-a-plugin.html.md
This guide explains how to install a plugin in the Workarea platform.
Although there may be some overlap with how this works in the rest of
the Rails community, there is no mention of how to connect to our
private gem server, which is not something most Rails developers know
how to do. It addresses the lack of mentions for the
`$BUNDLE_GEMS__WEBLINC__COM` environment variable in our documentation,
which is a knowledge gap for newcomers to Workarea and/or using private
gem servers.
=> Add Guide for Installing Plugins

.github/workflows/ci.yml, core/app/models/workarea/segment/rules/traffic_referrer.rb, core/workarea-core.gemspec
This method call fails with a `TypeError` on any Ruby version lower than
2.5.0, when the method was changed to support `nil` values in its
arguments. To address this, call `#to_s` on all arguments passed into
the `#casecmp?` calls in `Segment::Rules::TrafficReferrer`. This
prevents an out-of-box test failure if you are running tests on Ruby
2.4.x. Additionally, this commit adds a test matrix to the build that
will ensure all code is tested against the latest versions of Ruby
2.4.x and Ruby 2.6.x, and any other Ruby versions that the platform may
support.
=> Fix `#casecmp?` in Traffic Referrer Segment Rule

admin/test/integration/workarea/admin/assets_integration_test.rb, admin/test/system/workarea/admin/assets_system_test.rb, core/app/services/workarea/direct_upload.rb, core/test/services/workarea/direct_upload_test.rb
Workarea previously replaced the existing CORS configuration on the S3
bucket used for storing direct uploads with its own, which caused issues
for environments that share an S3 bucket between servers (such as ad-hoc
demo servers or low-traffic "all-in-one" instances). Instead of
replacing the entire configuration, Workarea now reads the existing
allowed hosts configuration and appends its own onto the end, preserving
the configuration that previously existed. This should address the
problem wherein if another server attempts a direct upload, it can
revoke the access from previous servers to upload to the S3 bucket,
since they were no longer in the CORS configuration.
=> Fix Overwriting CORS Rules for S3 Direct Uploads

admin/test/integration/workarea/admin/content_page_copies_integration_test.rb, core/app/services/workarea/copy_page.rb
When copying a page, the content associated with that page was not
being copied properly. This resulted in unexpected sharing of content
blocks for both pages, with changes to one page affecting both in
tandem. To resolve this, remove any other content records that exist
prior to cloning and saving the content record from the copied page.
Additionally, map over all content blocks and ensure they are cloned so
that the block IDs are not shared between documents.
=> Fix Content Block Copying

admin/app/helpers/workarea/admin/content_helper.rb, admin/test/helpers/workarea/admin/content_helper_test.rb
In the `options_for_category` method, Workarea did not previously check
for whether a category exists, resulting in Mongoid throwing a
`DocumentNotFound` error when encountering the method and causing a 500
error in the real world. This has now been resolved by rewriting the
code to check for whether the model was found before proceeding.
`options_for_category` will now return `nil` early when this occurs.
=> Handle Deleted Categories in Category Options

admin/app/controllers/workarea/admin/content_blocks_controller.rb, core/app/models/workarea/content/block.rb, core/app/models/workarea/content/block_draft.rb, core/app/models/workarea/content/block_type.rb, core/app/models/workarea/content/block_type_definition.rb, core/app/models/workarea/content/preset.rb, core/lib/workarea/configuration/content_blocks.rb, core/test/models/workarea/content/block_name_test.rb, core/test/models/workarea/content/block_type_definition_test.rb, docs/source/articles/content.html.md, storefront/test/integration/workarea/storefront/content_blocks_integration_test.rb, storefront/test/performance/workarea/storefront/pages_performance_test.rb, storefront/test/view_models/workarea/storefront/content_block_view_model_test.rb
Storing these in `Workarea.config` breaks when combined with the
multisite plugin because `Workarea.config` gets copied to the site as
part of the creating the site. Since creating the site happens during
initialization and the blocks typesaren't set on `Workarea.config`, you
end up with an empty configuration for block types.
Storing these elsewhere ensures they are set regardless of how
`Workarea.config` has been copied during initialization.
Reported in Disource here: https://discourse.workarea.com/t/multi-site-and-testing/1778/3
=> Don't store content block types in configuration

admin/test/integration/workarea/admin/assets_integration_test.rb, admin/test/system/workarea/admin/assets_system_test.rb, testing/lib/workarea/test_case.rb
It's annoying and unnecessary to have to stub this for every test that
uses an asset picker.
WORKAREA-209
=> Fix S3 CORS in tests

admin/app/views/workarea/admin/releases/index.html.haml, admin/config/locales/en.yml
The `#changesets_for_releasable` query cannot be optimized any further
without using some kind of aggregation. Remove it from the index so it
won't cause performance problems.
=> Remove Changes Count in Releases Index

admin/app/view_models/workarea/admin/pricing_sku_view_model.rb, admin/app/views/workarea/admin/pricing_skus/index.html.haml, admin/config/locales/en.yml, admin/test/view_models/workarea/admin/pricing_sku_view_model_test.rb
The price display in the Pricing SKUs index is somewhat confusing, and
would show different "Regular Price" data depending on the sale state of
the SKU. To resolve this, replace the two price columns with "Sell
Price", a column that renders a price range if there are multiple prices
set on the SKU, and indicates that it's always going to show the price
that a SKU is being sold for. Otherwise, it will just show the `#sell`
price of the SKU.
=> Display Price Range in Pricing SKUs Table

docs/source/articles/configure-product-image-sizes-and-processing.html.md
Dragonfly link had an extra trailing forward-slash, breaking the link
=> Fixing Dragonfly Link

admin/app/controllers/workarea/admin/create_segments_controller.rb
The "Setup" page link sent users to the edit action, which has no
template associated with it. This resulted in an `UnknownFormat` error
appearing in development and a blank page in production. Workarea now
renders the `:setup` action's template when going back to the setup
page so this will render properly with the right information in the
form.
=> Render Setup When Link is Clicked in Segment Workflow

core/app/seeds/workarea/orders_seeds.rb
Workarea now provides random values for street address, city, and state.
All addresses are still in the US, however, so they will still validate
with default configuration. This provides more diverse seed data that
better reflects the real-life admin.
=> Randomize Addresses In Seeds

admin/app/view_models/workarea/admin/insights/product_view_model.rb, admin/test/view_models/workarea/admin/insights/product_view_model_test.rb
When calculating the average price for a product in its insights,
Workarea was previously using the amount of orders the product appears
in as a divisor. This will not show the correct average price of a
product unless every order only has a quantity of 1, since it includes
the total price of the item rather than its unit price. To make this
number accurately reflect the average price paid per unit on a product,
Workarea now uses the number of units sold as the divisor when
calculating the average unit price of a product.
=> Divide By Units Sold in Average Price Calculation

admin/app/views/workarea/admin/reports/timeline.html.haml
Workarea now ensures that the "Name" of a custom event is filled in
before submitting the form.
=> Validate Custom Event Name

storefront/app/view_models/workarea/storefront/search_view_model.rb, storefront/test/view_models/workarea/storefront/search_view_model_test.rb
This can heppen if Predictor and Elasticsearch both return a similar
query suggestion.
=> Fix duplicate suggested searches

core/app/seeds/workarea/insights_seeds.rb
Seeds were only generating insights for a single previous week
and month which caused some insights that rely on historical data
to not be generated i.e. trending products and searches.
WORKAREA-166
=> Generate weekly and monthly insights for historical data

admin/test/integration/workarea/admin/jump_to_integration_test.rb, core/app/models/workarea/search/admin.rb, core/lib/workarea/configuration.rb
This improves results by limiting the number of results that will show
per-type. This allows the user to see a more diverse set of results
instead of being overwhelmed by many matches in the top types.
=> Improve admin jump to search result types

admin/app/controllers/workarea/admin/application_controller.rb, admin/test/integration/workarea/admin/application_integration_test.rb, admin/test/integration/workarea/admin/index_tracking_integration_test.rb
When `.json` requests are made against the admin, the
`#track_index_filters` callback was previously saving off the full path,
resulting in issues with the back-linking on the admin UI. To resolve
this, Workarea no longer considers `.json` requests on the index page to
be a valid `session[:last_index_path]`.
=> Prevent Tracking Index Filters on JSON Requests

admin/app/assets/javascripts/workarea/admin/modules/datetimepicker_fields.js, admin/app/assets/javascripts/workarea/admin/templates/datetime_picker.jst.ejs, admin/app/views/workarea/admin/reports/timeline.html.haml
Ensure the hidden input storing the value for the dateTimePicker is
`:required`, which prevents the form from saving. This value is also
passed down into the template UI created by the JS module in order to
make sure the user gets some visual feedback.
=> Validate Date In Timeline Report Custom Events

admin/test/integration/workarea/admin/jump_to_integration_test.rb, core/app/models/workarea/search/admin.rb
This adds updated_at as a sort in jump to so most recent results show at
the top within their type. The types are still sorted the same.
=> Sort jump to results by last updated_at (within each type)

core/app/queries/workarea/search/product_entries.rb, core/test/queries/workarea/search/product_entries_test.rb
When entries are overridden to return multiple results _and_ there are
release changes for the product, the results weren't being flattened.
Fixes #405
=> Fix product search entries flattening

core/lib/workarea/geolocation.rb, core/test/lib/workarea/geolocation_test.rb, core/test/models/workarea/segment/rules/geolocation_test.rb
This was playing a little fast and loose with matching, causing CA to
match for California and Canada, IL to match for Illinois and Israel,
etc.
Matching only based on IDs chosen from the UI fixes these problems.
=> Tighten up segment geolocation matching rule

core/app/models/workarea/data_file/csv.rb, core/test/models/workarea/data_file/csv_test.rb
We hit a scenario where someone named a field `type`, so this change
updates the CSV import/export to use `_type` instead of `type` as the
class name for the model. This follows Mongoid attribute conventions.
This is a breaking change. Imports specifying classes will need to
update their fields.
=> Allow for fields named "type" in CSV import/export

admin/app/views/workarea/admin/releases/list.html.haml, admin/test/system/workarea/admin/releases_system_test.rb, core/app/queries/workarea/search/admin_releases.rb
Finding a release used previously based on when it was published is a
typical use case, so this makes it much easier.
=> Add filtering release by published date on the list view

core/app/workers/workarea/synchronize_user_metrics.rb
It's important this be kept in sync as real-time as possible, so we need
to avoid the Sidekiq retry delay where possible.
=> Fix duplicate key errors in metrics synchronization

admin/app/assets/javascripts/workarea/admin/modules/categorized_autocomplete_fields.js
This prevents locale from being included in the path to load results.
=> Fix harded JS path for admin jump to dropdown

storefront/app/views/workarea/storefront/fulfillment_mailer/shipped.html.haml
This commit fixes that fulfillment shipped mailer template is using cancellation header.
=> Fix fulfillment shipped mailer template

storefront/app/controllers/workarea/storefront/current_checkout.rb, storefront/test/integration/workarea/storefront/accounts_integration_test.rb, storefront/test/integration/workarea/storefront/current_checkout_integration_test.rb
No need for the extra cookie if the order isn't persisted. Note this
doesn't actually affect functionality.
=> Remove extra order ID cookie

core/app/services/workarea/direct_upload.rb, core/test/services/workarea/direct_upload_test.rb
The caching continues to give us problems, and this isn't a high-traffic
part of the system so there isn't a practical need for it.
=> Remove caching from direct upload CORS requests

core/app/workers/workarea/process_import.rb, core/test/workers/workarea/process_import_test.rb
When an import fails due to a missing `DataFile::Import` document, the
`ProcessImport` worker will raise a nil error due to the ensure. This
fixes by ensuring the `DocumentNotFound` error gets raised.
=> Fix incorrect import errors

storefront/app/controllers/workarea/storefront/checkout/addresses_controller.rb, storefront/test/integration/workarea/storefront/checkouts_integration_test.rb
A flash error incorrectly showed when the order doesn't require shipping,
and addresses are updated.
=> Fix incorrect shipping options error flash message

core/app/models/workarea/releasable.rb, core/test/models/workarea/releasable_test.rb
When reloading a model to get an instance for a release, if the model
had already been loaded, a cached version of the model was returned.
This causes incorrect values on the instance you thought you were getting
for a release.
This first manifested as a bug where adding a featured product that
had a release change to make it active caused reindexing to make it
active but it shouldn't have been.
=> Fix query caching in Releasable

core/workarea-core.gemspec
This fixes rack-attack keys without TTLs set piling up in Redis. This has caused hosting problems.
=> Bump rack-attack to latest version

core/app/models/workarea/search/admin/pricing_discount.rb
A custom discount may be implemented that doesn't use promo codes.
=> Don't assume promo codes for indexing discounts

core/app/workers/workarea/reindex_release.rb, core/test/workers/workarea/reindex_release_test.rb
When releases get rescheduled, the storefront index can end up with
duplicate and/or incorrect entries. This adds a worker which updates the
index with minimal querying/updating.
=> Fix storefront indexing when releases are rescheduled

admin/app/assets/javascripts/workarea/admin/modules/release_calendar_placeholders.js, admin/app/controllers/workarea/admin/releases_controller.rb
This was caused by legacy timezone code that's irrelevant since we
shifted to a fix server-side timezone for the admin.
=> Fix releases shifting day on the calendar when scrolling

core/workarea-core.gemspec
This fixes an irrelevant bundler-audit CVE warning, and adds/updates a bunch of Geocoder lookup options. See https://github.com/alexreisner/geocoder/blob/master/CHANGELOG.md for more info.
=> Bump Geocoder

core/app/workers/workarea/index_release_schedule_change.rb, core/test/workers/workarea/index_release_schedule_change_test.rb
When a release is deleted, its changes must be reindexed to fix previews
for releases scheduled after it. This manifests as duplicate products
when previewing releases.
=> Fix index duplicates after a release is removed

admin/app/view_models/workarea/admin/code_list_view_model.rb, admin/app/views/workarea/admin/pricing_discount_code_lists/_cards.html.haml, admin/app/views/workarea/admin/pricing_discount_code_lists/promo_codes.html.haml, admin/test/view_models/workarea/admin/code_list_view_model_test.rb
Previously, promo codes could only be generated once through the admin,
so rendering the count of all promo codes as the count requested to be
generated was working out. However, as CSV imports and API updates became
more widespread, this began to break down as the `#count` field would
have to be updated each time a new set of promo codes were added.
Instead of reading from this predefined field on the code list, render
the actual count of promo codes from the database on the code list and
promo codes admin pages.
=> Fix Promo Code Counts in Admin

admin/app/views/workarea/admin/facets/_applied.html.haml
When rendering the applied filters, wrap the given facet value in
the `facet_value_display_name` helper, ensuring that the value rendered
is always human readable. This addresses an issue where if the applied
filter value is that of a BSON ID, referencing a model somewhere, the
BSON ID was rendered in place of the model's name.
=> Use Display Name For Applied Facet Values

admin/app/views/workarea/admin/create_segments/setup.html.haml
The setup form for the new custom segment workflow did not include the
ID of an existing segment (if persisted) in the form when submitted,
causing multiple duplicate segment records to be created when users go
back to the setup step in the workflow. None of the other steps are
affected because the ID appears in the URL, but the setup step does a
direct POST to `/admin/create_segments`, thus causing this problem.
=> Fix Segments Workflow Setup Duplication

core/app/models/workarea/search/storefront/category_query.rb, core/test/models/workarea/search/storefront/category_query_test.rb
A category can have orphan changesets (from deleted releases) that cause
an error when indexing the percolation document for that category.
=> Fix indexing categorization changesets for deleted releases

admin/app/views/workarea/admin/releases/show.html.haml, admin/config/locales/en.yml
Due to the previewing in the search index, previewing a published and
unscheduled release can cause issues that require it to go through
scheduling to get reindexed.
=> Disable previewing for already published, unscheduled releases

testing/lib/workarea/integration_test.rb, testing/lib/workarea/performance_test.rb, testing/lib/workarea/system_test.rb, testing/lib/workarea/test_case.rb
This ensures individual tests monkeying around with Geocoder config will
get restored before the next test runs.
=> Reset Geocoder between tests

admin/app/views/workarea/admin/create_users/admin.html.haml
This allows a plugin (such as API) to specify permissions categories when admins are either editing or creating a user.
=> Add Permissions Append Point to User Workflow

core/lib/workarea/core.rb, core/lib/workarea/ext/jbuilder/jbuilder_cache.rb
Previously, admins were not able to see up-to-date data in API requests due to the `#cache!` method in Jbuilder not being patched to skip caching when an admin is logged in. To resolve this, Workarea now applies the same patch to Jbuilder as it does to ActionView. Reading from the cache is now skipped if you're logged in as an admin, and cache keys are appended with the configured `Cache::Varies` just the same as in regular Haml views.
=> Patch Jbuilder to Support Varying Cache

admin/app/views/workarea/admin/content/_edit.html.haml, admin/config/locales/en.yml
Remove the current content name and replace it with a static label indicating what the `<select>` menu to the right of it is selecting, which is the current content area. This UI only displays when there are multiple areas for a given `Content`.
=> Improve Content Area Select UX

core/lib/workarea/configuration/administrable_options.rb
Accessing administrable options on `Workarea.config` can produce unexpected results if you don't use the traditional method accessor syntax. For example, an admin field like this:
```ruby
Workarea::Configuration.define_fields do
field :my_admin_setting, type: :string, default: 'default value'
end
```
...will only be available at `Workarea.config.my_admin_setting`:
```ruby
Workarea.config.my_admin_setting # => "default value"
Workarea.config[:my_admin_setting] # => nil
```
To resolve this, the code for fetching a key's value from the database has been moved out of `#method_missing` and into an override of `#[]`.  [Since the OrderedOptions superclass already overrides this](https://github.com/rails/rails/blob/fbe2433be6e052a1acac63c7faf287c52ed3c5ba/activesupport/lib/active_support/ordered_o …
=> Fix `Hash#[]` Access On Administrable Options

storefront/test/integration/workarea/storefront/place_order_integration_test.rb
Currently, decorating the PlaceOrderIntegrationTest to edit the way its set up (such as when adding an additional step) is impossible, you have to basically copy everything out of the `setup` block and duplicate it in your tests. Setup blocks should be methods anyway, so convert this to a method and allow it to be decorated in host apps.
=> Setup PlaceOrderIntegrationTest in a Method

core/app/models/workarea/payment.rb, core/lib/workarea/configuration.rb, storefront/app/controllers/workarea/storefront/users/credit_cards_controller.rb
To prevent an unnecessary decoration of the `Payment` class, make the attributes used in `Payment#set_credit_card` configurable. This configuration is reused on the `Users::CreditCardsController` for adding a new saved credit card to a user's account.
=> Configure Sliced Credit Card Attributes

docs/source/articles/b2b-overview.html.md
Point it to https://demo.workarea.com since we already have B2B installed on the regular demo instance.
=> Fix B2B Demo Link

docs/source/cli.html.md
The clone URL for the `homebrew-taps` repo on Stash required SSH access to the repo, whereas read-only members may not have that level of access. Update this to include a more accessible URL.
Kinda weird that we don't ever indicate that you actually need to be on Commerce Cloud to use this thing, but maybe that's a discussion we should have down the road...
=> Fix Clone URL in CLI Documentation

storefront/app/views/workarea/storefront/order_mailer/_summary.html.haml
This append point in the `order_mailer/_summary.html.haml` seems to have been added by mistake in v3.5 (by me) with the fulfillment sku additions. Using this append in the mailer and the view causes issues if the append point is used to add a partila with a `_path` helper. From what I can tell it seems like it was probably a copy/pasta and not intentional
https://stash.tools.weblinc.com/projects/WL/repos/workarea/commits/bd21334c0c1a4cdf3f7db381c95298bddcdd91cd#storefront/app/views/workarea/storefront/order_mailer/_summary.html.haml
=> Remove view append from mailer

core/workarea-core.gemspec
The vulnerability won't affect Workarea in use, but it'll be easier to fix builds doing this.
=> Bump Chartkick to fix bundler audit warning

core/app/models/workarea/checkout.rb, core/test/models/workarea/checkout_test.rb
For APIs and other consumers of the Checkout model, return a boolean response from the `#update` method to signify whether the operation succeeded or failed. This response is used directly in the API to return an `:unprocessable_entity` response code when an update operation fails.
=> Return Status of `Checkout#update`

core/app/models/workarea/order.rb, core/app/models/workarea/order/item.rb, core/app/models/workarea/order/items_extension.rb, core/app/services/workarea/add_multiple_cart_items/item.rb, core/lib/workarea/configuration.rb, core/test/models/workarea/order_test.rb, storefront/app/controllers/workarea/storefront/cart_items_controller.rb
When adding an item that already exists in the cart, Workarea previously checked the SKU and customizations on the item before deciding whether to actually build a new `Order::Item` or update the one found in place.  This is somewhat limiting for plugins such as `Workarea::Subscriptions`, which add more data to an order item that is expected to be updated in place (so long as the item is a subscription). To address this, a configuration setting has been added which plugins and apps can append to in order to affect the "uniqueness" of a particular order item. By appending to this config, both host apps and plugins can tell the `Order::ItemsExtension#find_existing` method to factor in additional fields on the order when determining whether a given item exists in the cart or not.
=> Configurable Order Item Equivalence Attributes

core/app/models/workarea/data_file/csv.rb, core/test/models/workarea/data_file/import_test.rb
Trying to update an embedded model via CSV import with a release causes
an existing changeset for the root model to get destroyed. This happens
because the CSV import calls `#save` on the root, which has no changes
so it removes the changeset.
This patch fixes by iterating over the models the CSV row might affect
and calling `#save` on the embedded ones first (if necessary) to ensure
the changesets get correctly created and to avoid calling the save on
the root without changes which removes the existing changeset.
=> Fix missing release changes for CSV importing with embedded models

core/app/mailers/workarea/application_mailer.rb, core/lib/generators/workarea/install/install_generator.rb, core/lib/generators/workarea/install/templates/initializer.rb.erb, core/test/generators/workarea/install_generator_test.rb, core/test/mailers/workarea/application_mailer_test.rb
Ports aren't part of hosts, this causes problems when the value is used like a true host.
=> Remove port from host configuration in installer

core/lib/tasks/tests.rake
Fixes missing underscores in the task names. Note this is breaking, if you are depending on one of the tasks, you'll need to update to the correct plugin slug.
This has been driving me nuts.
=> Fix naming on plugin-specific test tasks

core/app/queries/workarea/search/admin_search.rb, core/app/queries/workarea/search/admin_sorting.rb, core/test/queries/workarea/search/admin_search_test.rb
The query for an admin index page can end up inadvertantly introduce a
scoring variation, which can cause results to not match the `updated_at`
default sort.
This makes `updated_at` the true default sort, and allows the general
admin search to override, where `_score` is still the desired default
sort.
=> Fix wrong sorting on default admin index pages

admin/app/controllers/workarea/admin/configurations_controller.rb
Admins without "Settings" access are no longer able to access the administrable configuration settings defined in a Workarea application's initializer.
=> Add Permissions To Admin::ConfigurationsController

core/config/initializers/00_configuration.rb, core/lib/generators/workarea/install/templates/initializer.rb.erb, core/lib/workarea/configuration.rb, core/test/generators/workarea/install_generator_test.rb
The hard-coded `config.email_from` and `config.email_to` settings conflict with the out-of-box administrable configuration for the "Email From" and "Email To" settings. This causes a warning for admins that explain why the settings on "Email To" and "Email From" won't take effect. Since the whole purpose of moving these settings to admin configuration was to let admins actually change them, the `config.email_from` and `config.email_to` settings have been removed from both default configuration and the `workarea:install` generator.
=> Fix Admin Configuration for Email Addresses

core/lib/workarea/configuration/image_processing.rb, core/lib/workarea/warnings.rb
Trying to load the ruby-vips gem on an old version of libvips will
error, this shows a nicer warning.
=> Ensure a supported version of libvips

admin/app/controllers/workarea/admin/bulk_variant_saving.rb
When creating a new product through the workflow, setting the "Inventory" on a particular SKU would still cause the `Inventory::Sku` to be created with the "Ignore" policy rather than "Standard". Setting inventory on a SKU now automatically causes the `Inventory::Sku` record to be created with a policy of "Standard" so as to deduct the given inventory to the varaint. When no inventory is given, Workarea will fall back to the default of "Ignore".
=> Set Default Inventory Policy to "Standard" in Create Product Workflow

admin/app/controllers/workarea/admin/shipping_skus_controller.rb, admin/app/view_models/workarea/admin/shipping_sku_view_model.rb, admin/app/view_models/workarea/admin/variant_view_model.rb, admin/app/views/workarea/admin/catalog_variants/index.html.haml, admin/app/views/workarea/admin/shared/_primary_nav.html.haml, admin/app/views/workarea/admin/shipping_skus/_aux_navigation.html.haml, admin/app/views/workarea/admin/shipping_skus/_cards.html.haml, admin/app/views/workarea/admin/shipping_skus/_summary.html.haml, admin/app/views/workarea/admin/shipping_skus/edit.html.haml, admin/app/views/workarea/admin/shipping_skus/index.html.haml, admin/app/views/workarea/admin/shipping_skus/new.html.haml, admin/app/views/workarea/admin/shipping_skus/show.html.haml, admin/config/locales/en.yml, admin/config/routes.rb, admin/test/integration/workarea/admin/shipping_skus_integration_test.rb, admin/test/system/workarea/admin/shipping_skus_system_test.rb, core/app/models/workarea/search/admin/shipping_sku.rb, core/app/models/workarea/shipping/sku.rb, core/app/queries/workarea/search/admin_shipping_skus.rb, core/config/locales/en.yml, core/lib/workarea/configuration.rb
This adds an interface to Shipping SKUs from within the admin. Based on the Pricing SKUs admin UI, it allows for administration of a SKU's weight and dimensions. This information is used by ActiveShipping in order to generate a package and automatically obtain shipping rates for the item represented by this SKU.
=> Shipping SKUs Admin UI

core/app/models/workarea/order/item.rb, core/test/models/workarea/order/item_test.rb
Methods such as #shipping? and #download? defined from available
fulfillment policies now call #fulfilled_by rather than being called
by it. This allows #fulfilled_by? to be modified to support more
complex scenarios like bundled items from kits.
WORKAREA-273
=> Make Order::Item#fulfilled_by? the canonical check of item's fulfillment

admin/app/views/workarea/admin/catalog_variants/edit.html.haml, admin/app/views/workarea/admin/catalog_variants/new.html.haml, admin/config/locales/en.yml
This removes the "Comma separated: just, like, this" messaging and tooltip that explains more about comma-separated fields for filters and details. Options do not have these same constraints, and this help bubble just serves as a point of confusion for admins.
=> Remove CSV Messaging For Options Fields

admin/test/system/workarea/admin/impersonation_system_test.rb
This test was broken because of new additions to the attributes card
causing the content to push out of view. It's a minor assertion, so
removing it seems acceptable given there is more in the test to prove
impersonation has stopped.
=> Fix broken impersonation test

core/app/controllers/workarea/current_tracking.rb, core/app/controllers/workarea/impersonation.rb, core/lib/workarea/visit.rb, core/test/integration/workarea/authentication_test.rb, storefront/test/integration/workarea/storefront/impersonations_integration_test.rb
Not managing the email cookie and unintentional merging of metrics leads
to incorrect values in the admin.
=> Fix incorrect tracking and metrics after impersonation

admin/app/assets/stylesheets/workarea/admin/components/_toggle_button.scss, admin/app/views/workarea/admin/shared/_toggle_button.html.haml
When a toggle button is disabled, it should reflect that visually
instead of just looking like it should be functional.
=> Improve display of disabled toggles

admin/app/views/workarea/admin/catalog_product_images/edit.html.haml
When an image does not include an option, the edit page errors because `#parameterize` cannot be called on `@image.option` since that is returning `nil`. Additionally, the line of code in which this is called is meant to set an ID attribute on the element for which an image is rendered. There doesn't seem to be anything in our codebase that uses this, and furthermore since there's no validation for unique options per set of product images, this could cause a duplicate ID error in certain scenarios. To resolve this, the ID attribute has been removed from this `<img>` tag.
=> Fix Editing Product Images in Admin

admin/app/controllers/workarea/admin/impersonations_controller.rb, admin/app/views/workarea/admin/toolbar/show.html.haml, admin/config/locales/en.yml, admin/test/integration/workarea/admin/impersonations_integration_test.rb, admin/test/system/workarea/admin/impersonation_system_test.rb
Currently we redirect to the user's show page, which can be pretty
disorienting.
=> Redirect back to the previous page after stopping impersonation

admin/app/views/workarea/admin/configurations/types/_array.html.haml, admin/app/views/workarea/admin/configurations/types/_duration.html.haml, admin/app/views/workarea/admin/configurations/types/_encrypted.html.haml, admin/app/views/workarea/admin/configurations/types/_float.html.haml, admin/app/views/workarea/admin/configurations/types/_integer.html.haml, admin/app/views/workarea/admin/configurations/types/_select.html.haml, admin/app/views/workarea/admin/configurations/types/_string.html.haml, admin/app/views/workarea/admin/configurations/types/_symbol.html.haml, core/app/models/workarea/configuration/params.rb, core/lib/workarea/configuration/administrable/field.rb, core/test/lib/workarea/configuration/administrable/field_test.rb, core/test/models/workarea/configuration/params_test.rb, docs/source/articles/configuration-fields.html.md, docs/source/upgrade-guides/workarea-3-6-0.html.md
This removes the `allow_blank` option from the configuration DSL and adds
the `required` in its place. This is done to align with developer
expectations we've experienced.
=> Add required option to config DSL in place of allow blank

admin/app/views/workarea/admin/tax_categories/_cards.html.haml, admin/app/views/workarea/admin/tax_rates/edit.html.haml, admin/app/views/workarea/admin/tax_rates/index.html.haml, admin/app/views/workarea/admin/tax_rates/new.html.haml, admin/test/system/workarea/admin/tax_categories_system_test.rb, core/app/models/workarea/tax/rate.rb
The `:step` values of the new/edit forms and precision configuration for `#number_to_percentage` were not only rounding certain tax rates to an incorrect number, but were also showing a bunch of insignificant zeroes in the admin for tax rates. To resolve this, configure `#number_to_percentage` to have 3-decimal precision, and strip all insignificant zeroes from the display, leaving the admin with a much nicer percentage display than what was presented before.
**Before:**
**After:**
Here's another pic of all the different precision levels:
=> Fix Precision of Tax Rates UI

docs/source/articles/http-caching.html.md
Add documentation explaining why one might want to ignore query string params in `Rack::Cache`, how to do it in a Workarea environment, and which plugins will do it for you.
=> Notate Rack::Cache Ignore Params In Documentation

docs/source/articles/decorate-and-write-tests.html.md, storefront/test/integration/workarea/storefront/store_credit_integration_test.rb
Add documentation explaining why the `setup` and `teardown` macros are recommended for use with Workarea to set up and teardown tests, as well as some clear examples of how to do this properly.
=> Clarify Test Setup and Teardown in Documentation

admin/test/system/workarea/admin/assets_system_test.rb, admin/test/system/workarea/admin/bookmarks_system_test.rb, admin/test/system/workarea/admin/bulk_actions_system_test.rb, admin/test/system/workarea/admin/comments_system_test.rb, admin/test/system/workarea/admin/content_system_test.rb, admin/test/system/workarea/admin/dashboard_system_test.rb, admin/test/system/workarea/admin/inventory_skus_system_test.rb, admin/test/system/workarea/admin/menus_system_test.rb, admin/test/system/workarea/admin/pricing_sku_prices_system_test.rb, admin/test/system/workarea/admin/recommendations_system_test.rb, admin/test/system/workarea/admin/releases_system_test.rb, admin/test/system/workarea/admin/taxonomy_system_test.rb, admin/test/system/workarea/admin/trash_system_test.rb, docs/source/articles/change-the-storefront-product-pricing-ui.html.md, storefront/test/system/workarea/storefront/content_system_test.rb, storefront/test/system/workarea/storefront/credit_cards_system_test.rb, storefront/test/system/workarea/storefront/navigation_system_test.rb, storefront/test/system/workarea/storefront/pagination_system_test.rb
This is a cherry pick from @jonmast's original PR here: #525 
I'd like to see the build pass before merging.
=> Remove unnecessary Capybara blocking when testing content is not present

docs/data/articles.yml, docs/source/articles/sequential-order-numbering.html.md
Add a section to the developer docs explaining how Workarea constructs order IDs, why sequential order numbering is generally ill-advised, as well as a solution for implementing the "vanity" side of the feature.
=> Add Sequential Order Numbering Guide

core/config/initializers/05_scheduled_jobs.rb, core/lib/workarea.rb, core/lib/workarea/configuration.rb, core/lib/workarea/configuration/administrable_options.rb, core/lib/workarea/scheduled_jobs.rb, core/lib/workarea/warnings.rb, core/test/lib/workarea/scheduled_jobs_test.rb
This was broken due to the admin-based configuration looking for a Mongo
connection.
=> Fix skip services

core/test/workers/workarea/status_reporter_test.rb
This test for the `StatusReporter` worker asserted `2`, which will never fail because `2` will never be falsy. Updated the assertion to use the intended `assert_equals`
=> Fix Test That Will Never Fail

core/app/controllers/workarea/current_referrer.rb, core/lib/workarea/core.rb, core/lib/workarea/ext/referer_parser/parser.decorator, core/test/lib/workarea/ext/referer_parser/parser_test.rb
Android App URLs have a special android-app:// scheme that is rejected by the currently released version of the referer-parser gem. The code in this patch already exists in the master branch of the gem, but this has not yet been released, and if Android users browse the storefront it can generate an error when collecting referer information.
Fixes #531
=> Patch RefererParser for Android URLs

core/app/queries/workarea/search/product_entries.rb
This allows easier reuse of this logic, specifically for the site
builder plugin we're working on.
=> Refactor product entries to allow accessing logic per-product

core/test/models/workarea/data_file/csv_test.rb
Improve this test so decorating ApplicationDocument to add a field won't
cause the test to break.
=> Make CSV test more robust to decorations

admin/app/assets/javascripts/workarea/admin/modules/new_navigation_taxons.js, admin/test/javascripts/fixtures/existing_navigation_taxon.html.haml, admin/test/javascripts/new_navigation_taxons_spec.js
The `WORKAREA.newNavigationTaxons` module was looking in the wrong place for the selected navigable item, therefore the `selected` var would always return `undefined`, causing the `navigable_id` param to be blank every time. Fix this by querying for the correct DOM node (the `[data-new-navigation-taxon]` element) and pulling the selected ID from its data.
Fixes #534
=> Prevent Clearing Out Navigable When Saving Taxons

core/app/models/workarea/release.rb, core/app/models/workarea/search/storefront.rb, core/app/models/workarea/search/storefront/product.rb, core/app/queries/workarea/product_releases.rb
Cleanup duplicate logic so decoration for product indexes can happen in
a single place.
WORKAREA-292
=> Fix release changeset indexing code duplication

admin/app/controllers/workarea/admin/impersonations_controller.rb, admin/test/integration/workarea/admin/impersonations_integration_test.rb, admin/test/system/workarea/admin/impersonation_system_test.rb
When ending an impersonation, this changes to allow redirecting to the referrer
if the return_to parameter isn't present. Better UX for ending
impersonations while working in the admin.
WORKAREA-293
=> Include referrer in ending impersonation redirect fallbacks

admin/app/views/workarea/admin/catalog_categories/edit.html.haml, admin/config/locales/en.yml
The selected `default_sort` of a category will be always used in the storefront. If the category contains featured products, this sort will be labelled "Featured", and this might prove confusing to some admins.  To resolve this, add a note just below the dropdown indicating what will occur when products are featured in the category.
=> Add Note To Category Default Sort Edit

admin/app/view_models/workarea/admin/bulk_action_product_edit_view_model.rb, admin/app/views/workarea/admin/bulk_action_product_edits/edit.html.haml, admin/app/views/workarea/admin/bulk_action_product_edits/review.html.haml, admin/config/locales/en.yml, admin/test/system/workarea/admin/bulk_actions_system_test.rb, core/app/models/workarea/bulk_action/product_edit.rb, core/app/models/workarea/bulk_action/product_edit/price_change.rb, core/app/models/workarea/bulk_action/product_edit/price_change/amount.rb, core/test/models/workarea/bulk_action/product_edit/price_change/amount_test.rb, core/test/models/workarea/bulk_action/product_edit/price_change_test.rb, core/test/models/workarea/bulk_action/product_edit_test.rb
When bulk editing products, Workarea previously allowed the admin to set pricing on all SKUs in bulk. This was always a flat amount, and all prices were updated to match that amount. To build upon this feature, bulk editing products will now enable admins to set a percentage or amount they wish to increase/decrease the prices by. This allows, for example, a merchandiser to mark up all products in their bulk edit query 20%, or mark down all products by $15. The existing functionality for setting these prices has also been preserved, and extended to allow for setting the price to a percentage of the existing price, such as setting the price of a $20 to 20%, which would cause the product's price to be $4.
**Edit:**
**Review:**
=> Add Multiplier for Bulk Editing Product Pricing

admin/app/view_models/workarea/admin/user_view_model.rb, admin/test/view_models/workarea/admin/user_view_model_test.rb
When looking up recent orders for a user in the admin, also include any guest orders placed with the same email address. This fixes a discrepancy between the amount of orders seen in admin for a given user, and the amount of orders attributed to a user within insights, as insights treat all orders with the same email address as coming from the same user.
=> Include Guest Orders In Admin For Users

core/lib/workarea/changelog.rake
This change will allow starting commit messages with the word Revert
without the changelog task ignoring the commit.
=> Be more specific when matching reverts in changelogs

core/app/models/workarea/metrics/user.rb, core/test/models/workarea/metrics/user_test.rb, core/test/workers/workarea/update_email_test.rb
This will ensure the consistency of user-based reports.
=> Delete old user metrics after merging

core/app/controllers/workarea/current_tracking.rb, core/app/models/workarea/metrics/user.rb
Merging all metrics has caused a lot of confusion in testing, and the
only core use-case this matters for is recent views. So this change only
merges recent views when metrics are updated.
=> Only merge recent views on tracking updates

core/app/models/workarea/release/changeset.rb
Mongo will raise when index names exceed a certain length. For example,
having a long Workarea.config.site_name could cause this.
=> Shorten index name

core/app/models/workarea/search/admin.rb
Ruby raises when nil is compared, so default these values.
I struggled to test this since it would require a bad admin search model implementation.
https://sentry.tools.weblinc.com/weblinc/workarea-v3-qa/issues/5767658/?query=is:unresolved
=> Fix missing jump to positions breaking jump to

storefront/app/controllers/workarea/storefront/cart_items_controller.rb, storefront/test/integration/workarea/storefront/cart_items_integration_test.rb
The `@cart` instance variable was only being conditionally defined if `current_order.add_item` succeeded. This caused an error if `#add_item` happens to fail when calling `POST /cart/items` from the storefront, resulting in a 500 error. To prevent this error, the definition of this variable has been moved above the condition.
=> Fix Missing Instance Variable In Cart Items View

storefront/app/view_models/workarea/storefront/product_view_model.rb, storefront/test/view_models/workarea/storefront/product_view_model_test.rb
Typically, custom product templates use their own subclass of `Workarea::Storefront::ProductViewModel`, but this isn't supposed to be necessary if there's no custom logic that needs to be in the view model layer. However, when developers tried to add a custom template without the view model, they received an error. To prevent this, Workarea will now catch the `NameError` thrown by `Storefront::ProductViewModel.wrap` in the event of a custom product template not having a view model defined.
=> Prevent Error on Missing Custom Template View Model Class

testing/lib/workarea/integration_test.rb, testing/lib/workarea/performance_test.rb, testing/lib/workarea/system_test.rb
This ensures the proper search indexes are in place when you switch
locales for an integration test.
=> Fix Elasticsearch indexes when changing locales in tests

admin/app/helpers/workarea/admin/application_helper.rb, admin/app/views/workarea/admin/navigation_redirects/index.html.haml, admin/config/locales/en.yml
This has confused developers a couple of times, so hopefully adding a
warning will help.
=> Add warning to inform developers why redirects aren't working locally

admin/app/views/workarea/admin/content/advanced.html.haml, admin/config/locales/en.yml, core/app/queries/workarea/metadata.rb, core/config/initializers/00_configuration.rb, core/test/queries/workarea/metadata_test.rb
This allows someone to disable all automated SEO data from being
generated.
=> Add configuration for global control over automated SEO data

admin/app/helpers/workarea/admin/changesets_helper.rb, admin/test/helpers/workarea/admin/changesets_helper_test.rb
WORKAREA-310
Turns out [invline_svg has a fallback option](https://github.com/jamesmartin/inline_svg#options)
=> Use inline_svg fallback for missing releasable icons

admin/app/controllers/workarea/admin/create_release_undos_controller.rb, admin/test/integration/workarea/admin/create_release_undos_integration_test.rb
Because the changeset is the only getting saved when building an undo,
admin reindexing for the affected models isn't happening. This change
triggers callbacks to ensure any related side-effects happen.
=> Fix undo releases not causing models to reindex

admin/app/views/workarea/admin/configurations/show.html.haml, core/config/initializers/00_configuration.rb, core/lib/workarea/configuration/administrable/definition.rb, core/lib/workarea/configuration/administrable/fieldset.rb, core/lib/workarea/core.rb, core/workarea-core.gemspec, storefront/app/controllers/workarea/storefront/application_controller.rb, storefront/app/controllers/workarea/storefront/checkout/addresses_controller.rb, storefront/app/controllers/workarea/storefront/checkout/place_order_controller.rb, storefront/app/controllers/workarea/storefront/checkout/shipping_controller.rb, storefront/app/controllers/workarea/storefront/contacts_controller.rb, storefront/app/controllers/workarea/storefront/email_signups_controller.rb, storefront/app/controllers/workarea/storefront/recaptcha.rb, storefront/app/controllers/workarea/storefront/users/accounts_controller.rb, storefront/app/controllers/workarea/storefront/users/logins_controller.rb, storefront/app/helpers/workarea/storefront/recaptcha_helper.rb, storefront/app/views/layouts/workarea/storefront/application.html.haml, storefront/app/views/workarea/storefront/checkouts/addresses.html.haml, storefront/app/views/workarea/storefront/checkouts/payment.html.haml, storefront/app/views/workarea/storefront/checkouts/shipping.html.haml, storefront/app/views/workarea/storefront/contacts/show.html.haml, storefront/app/views/workarea/storefront/users/logins/new.html.haml, storefront/config/locales/en.yml, storefront/test/integration/workarea/storefront/accounts_integration_test.rb, storefront/test/integration/workarea/storefront/recaptcha_integration_test.rb, storefront/test/vcr_cassettes/recaptcha.yml
This change allows configuring reCAPTCHA v3 and/or v2 in the admin. It
is placed on critical site flows where we've noticed problems with bot
abuse.
While the primary intent is using reCAPTCHA v3, we allow v2 to be
configured to support challenging when a v3 verification fails.
=> Add reCAPTHCHA support

core/app/models/workarea/search/admin.rb, core/app/workers/workarea/index_admin_search.rb, core/test/workers/workarea/index_admin_search_test.rb
When embedded models are changed, their root documents weren't being
reindexed for admin search. This PR ensures admin indexing happens
correctly.
=> Fix admin indexing for embedded model changes

storefront/app/assets/javascripts/workarea/storefront/modules/dialog_buttons.js
This only worked if the URL had only one dot (before the file extension)
and no query parameters. Run it through the URL parser to provide more
robust handling.
=> Improve image URL detection for dialog_buttons

core/workarea-core.gemspec
Redcarpet released a security fix, so ensure using a version with that fix.
Redcarpet is only used to render help pages in the admin, so the vulnerability in Workarea is minimal.
=> Bump redcarpet version to fix security warnings

testing/lib/workarea/test_help.rb
Lowering the bcrypt cost lowers the time required to encrypt a password, at the cost of increasing the speed at which an attacker can try to crack the password. This is an acceptable tradeoff for improving performance of running tests. This shaves about 5 minutes off of the admin tests.
Hat tip to Jeff Yucis for discovery.
=> Improve password performance when running tests
